# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('manual', 'Manual')], default='mpesa', max_length=16)),
                ('provider', models.CharField(blank=True, default='mpesa', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('account_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('managed_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_payments', to='jobs.managedjob', verbose_name='managed job')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='payer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='quotes.quote', verbose_name='quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaSTKRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('response_code', models.CharField(blank=True, max_length=20, null=True)),
                ('response_description', models.TextField(blank=True, null=True)),
                ('customer_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPhoneConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('phone_number', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('quote_payment', 'Quote payment'), ('managed_job_payment', 'Managed job payment')], max_length=32)),
                ('consent_text', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_consents', to='payments.payment', verbose_name='payment')),
                ('stk_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_consents', to='payments.mpesastkrequest', verbose_name='M-Pesa STK request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_phone_consents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['quote', 'status'], name='payment_quote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['managed_job', 'status'], name='payment_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account_reference'], name='payment_account_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_stk_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['status'], name='mpesa_stk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentphoneconsent',
            index=models.Index(fields=['user', 'created_at'], name='phone_consent_user_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentphoneconsent',
            index=models.Index(fields=['payment', 'created_at'], name='phone_consent_payment_idx'),
        ),
    ]
