# Generated by Django 5.2.11 on 2026-09-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='quotes.quote', verbose_name='quote'),
        ),
        migrations.AddField(
            model_name='mpesastkrequest',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='payments.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='paymentphoneconsent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_consents', to='payments.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='paymentphoneconsent',
            name='stk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_consents', to='payments.mpesastkrequest', verbose_name='M-Pesa STK request'),
        ),
        migrations.AddField(
            model_name='paymentphoneconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_phone_consents', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['quote', 'status'], name='payment_quote_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['managed_job', 'status'], name='payment_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['account_reference'], name='payment_account_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['checkout_request_id'], name='mpesa_stk_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesastkrequest',
            index=models.Index(fields=['status'], name='mpesa_stk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentphoneconsent',
            index=models.Index(fields=['user', 'created_at'], name='phone_consent_user_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentphoneconsent',
            index=models.Index(fields=['payment', 'created_at'], name='phone_consent_payment_idx'),
        ),
    ]
