"""Quote-related constants and choice values."""

# Quote request statuses
DRAFT = "DRAFT"
SUBMITTED = "SUBMITTED"
PRICED = "PRICED"
SENT = "SENT"
ACCEPTED = "ACCEPTED"
REJECTED = "REJECTED"
EXPIRED = "EXPIRED"

# Quote item types
ITEM_TYPE_PRODUCT = "PRODUCT"
ITEM_TYPE_CUSTOM = "CUSTOM"

# Pricing modes
PRICING_MODE_SHEET = "SHEET"
PRICING_MODE_LARGE_FORMAT = "LARGE_FORMAT"

# Sides
SIDES_SIMPLEX = "SIMPLEX"
SIDES_DUPLEX = "DUPLEX"

# Color modes
COLOR_MODE_BW = "BW"
COLOR_MODE_COLOR = "COLOR"

# Charge units (finishing)
CHARGE_UNIT_PER_PIECE = "PER_PIECE"
CHARGE_UNIT_PER_SIDE = "PER_SIDE"
CHARGE_UNIT_PER_SHEET = "PER_SHEET"
CHARGE_UNIT_PER_SQM = "PER_SQM"
CHARGE_UNIT_FLAT = "FLAT"

# Apply-to-sides (finishing)
APPLY_SINGLE = "SINGLE"
APPLY_DOUBLE = "DOUBLE"
APPLY_BOTH = "BOTH"

# Imposition
DEFAULT_BLEED_MM = 3
