# Generated by Django 5.2.11 on 2026-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('shop_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('ONBOARDED', 'Onboarded'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Shop Lead',
                'verbose_name_plural': 'Shop Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
