# Generated by Django 5.2.11 on 2026-05-03 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('selected_product', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('suggested_min', models.PositiveIntegerField()),
                ('suggested_max', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('accepted', 'Accepted'), ('modified', 'Modified'), ('rejected', 'Rejected')], max_length=20)),
                ('modified_min', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_max', models.PositiveIntegerField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Action',
                'verbose_name_plural': 'Demo Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
