"""Seed data mirroring printy_workflow/data/printy.ts verbatim.

MANAGERS, PRINTERS and INITIAL_JOBS here reproduce the TS constants 1:1 so the
Django persistence layer and the (ported) frontend can never drift apart. The
`hist()` helper matches the TS `hist()` default (`at: NOW_AT` where
NOW_AT = "Today - 11:47").
"""

NOW_AT = "Today - 11:47"
SESSION_PRINTER_ID = "p-north"

MANAGERS = [
    {"id": "m-dale", "name": "Dale Carnegie", "initials": "DC", "tag": "Client whisperer - escalations", "onTime": 96, "hue": 36},
    {"id": "m-mj", "name": "MJ DeMarco", "initials": "MD", "tag": "Fastlane runs - speed", "onTime": 92, "hue": 200},
    {"id": "m-robert", "name": "Robert Cialdini", "initials": "RC", "tag": "Approvals and persuasion", "onTime": 89, "hue": 280},
    {"id": "m-eric", "name": "Eric Ries", "initials": "ER", "tag": "Lean batches - MVPs", "onTime": 84, "hue": 150},
    {"id": "m-peter", "name": "Peter Thiel", "initials": "PT", "tag": "Zero-to-one launches", "onTime": 97, "hue": 340},
]

PRINTERS = [
    {"id": "p-north", "name": "North Press Co.", "contact": "Jon Weber", "city": "Porto", "caps": ["Offset", "Digital", "Large format"], "verified": True, "rating": 4.9, "jobsDone": 212, "onTime": 98, "initials": "NP", "hue": 32},
    {"id": "p-halftone", "name": "Halftone Works", "contact": "Iris Kohler", "city": "Gdansk", "caps": ["Digital", "Short run"], "verified": True, "rating": 4.7, "jobsDone": 168, "onTime": 94, "initials": "HW", "hue": 190},
    {"id": "p-kobo", "name": "Kobo Bindery", "contact": "Ren Sato", "city": "Lyon", "caps": ["Binding", "Finishing", "Foiling"], "verified": True, "rating": 4.8, "jobsDone": 143, "onTime": 97, "initials": "KB", "hue": 265},
    {"id": "p-magenta", "name": "Magenta Mills", "contact": "Lena Marchetti", "city": "Milan", "caps": ["Flexo", "Packaging"], "verified": False, "rating": 4.2, "jobsDone": 3, "onTime": 0, "initials": "MM", "hue": 318},
]

BUYER_PERSONA = {
    "id": "b-ava",
    "name": "Ava Lindqvist",
    "role": "Head of Procurement",
    "company": "Studio North",
}


def hist(stage, actor, actor_role, note):
    """Mirrors the TS `hist()` factory: every event is stamped NOW_AT."""
    return {"stage": stage, "actor": actor, "actorRole": actor_role, "at": NOW_AT, "note": note}


INITIAL_JOBS = [
    {
        "id": "j1",
        "code": "PTY-1041",
        "title": "Aurora Heights - Launch Brochures",
        "product": "Tri-fold brochure - A4 to DL",
        "qty": 5000,
        "value": 2340,
        "buyerId": "b-ava",
        "buyerName": "Ava Lindqvist",
        "buyerCompany": "Studio North",
        "managerId": "m-dale",
        "printerId": "p-north",
        "specs": {"material": "170gsm silk - FSC", "colors": "CMYK both sides", "finish": "Tri-fold + matt lamination", "size": "A4 to DL (99x210)"},
        "proofImg": "/proofs/brochure.jpg",
        "status": "on-track",
        "custody": "held",
        "stage": "printing",
        "press": "ready",
        "progress": 0,
        "owner": {"name": "Jon Weber - North Press", "role": "Printer", "action": "Plates mounted - start the litho run", "waitingHrs": 3, "slaHrs": 8},
        "eta": "Fri 15 Nov - 16:00",
        "placedAt": "Fri 08 Nov - 09:12",
        "history": [
            hist("quote", "Ava Lindqvist", "Buyer", "Quote Q-2210 accepted - $2,340"),
            hist("artwork", "Mara Ivers", "Studio", "6pp imposed - 3mm bleed - PDF/X-4"),
            hist("approval", "Ava Lindqvist", "Buyer", "Proof v3 approved"),
            hist("payment", "Ava Lindqvist", "Buyer", "$2,340 moved into Printy Custody"),
            hist("production", "Dale Carnegie", "Manager", "Assigned North Press Co. - accepted 09:02"),
        ],
        "feed": [
            {"at": "Tue - 09:02", "who": "Jon Weber", "text": "accepted the job - 170gsm allocated from rack 4", "jobCode": "PTY-1041"},
            {"at": "Today - 08:41", "who": "Jon Weber", "text": "plates mounted, ink keyed. Ready to run.", "jobCode": "PTY-1041"},
        ],
    },
    {
        "id": "j2",
        "code": "PTY-1042",
        "title": "Bloom & Co - Kraft Swing Tags",
        "product": "Swing tag - 55x90 strung",
        "qty": 1200,
        "value": 410,
        "buyerId": "b-ava",
        "buyerName": "Ava Lindqvist",
        "buyerCompany": "Studio North",
        "managerId": "m-robert",
        "printerId": None,
        "specs": {"material": "400gsm uncoated kraft", "colors": "1c black + white ink", "finish": "Drilled and strung - round corners", "size": "55x90 mm"},
        "proofImg": "/proofs/swing-tags.jpg",
        "status": "at-risk",
        "custody": "awaiting",
        "stage": "approval",
        "press": None,
        "progress": None,
        "owner": {"name": "Ava Lindqvist", "role": "Buyer", "action": "Approve artwork proof v2", "waitingHrs": 19, "slaHrs": 24},
        "eta": "Tue 19 Nov",
        "placedAt": "Tue 12 Nov - 16:20",
        "history": [
            hist("quote", "Ava Lindqvist", "Buyer", "Quote Q-2216 accepted - $410"),
            hist("artwork", "Mara Ivers", "Studio", "Proof v2 - tagline kerning corrected"),
        ],
        "feed": [{"at": "Wed - 16:47", "who": "Mara Ivers", "text": "uploaded proof v2 - waiting on buyer approval", "jobCode": "PTY-1042"}],
    },
    {
        "id": "j3",
        "code": "PTY-1043",
        "title": "Meridian Coffee - Cup Sleeves",
        "product": "Cup sleeve - flexo 2c",
        "qty": 20000,
        "value": 1860,
        "buyerId": "b-ava",
        "buyerName": "Ava Lindqvist",
        "buyerCompany": "Studio North",
        "managerId": "m-mj",
        "printerId": None,
        "specs": {"material": "300gsm recycled kraft", "colors": "2c flexo (PANTONE 175C)", "finish": "Die-cut and glued", "size": "12-16oz taper"},
        "proofImg": None,
        "status": "on-track",
        "custody": "awaiting",
        "stage": "payment",
        "press": None,
        "progress": None,
        "owner": {"name": "Ava Lindqvist", "role": "Buyer", "action": "Release payment of $1,860", "waitingHrs": 2, "slaHrs": 4},
        "eta": "Mon 18 Nov",
        "placedAt": "Wed 13 Nov - 15:02",
        "history": [
            hist("quote", "Ava Lindqvist", "Buyer", "Quote Q-2219 accepted - $1,860"),
            hist("artwork", "Mara Ivers", "Studio", "Flexo separations - 2 plates"),
            hist("approval", "Ava Lindqvist", "Buyer", "Approved v1 first pass"),
        ],
        "feed": [{"at": "Today - 09:38", "who": "Ava Lindqvist", "text": "approved artwork - job moved to payment", "jobCode": "PTY-1043"}],
    },
    {
        "id": "j4",
        "code": "PTY-1044",
        "title": "Atlas Robotics - Welcome Boxes",
        "product": "Rigid conference box - foiled",
        "qty": 800,
        "value": 4720,
        "buyerId": "b-sara",
        "buyerName": "Sara Okafor",
        "buyerCompany": "Atlas Robotics",
        "managerId": "m-eric",
        "printerId": None,
        "specs": {"material": "2mm greyboard - 157gsm wrap", "colors": "CMYK + soft-touch", "finish": "Gold foil - magnetic close", "size": "320x240x80 mm"},
        "proofImg": None,
        "status": "overdue",
        "custody": "held",
        "stage": "production",
        "press": None,
        "progress": None,
        "owner": {"name": "Eric Ries", "role": "Manager", "action": "Assign a printer - capacity hold expires", "waitingHrs": 51, "slaHrs": 24},
        "eta": "Wed 20 Nov - at risk",
        "placedAt": "Mon 11 Nov - 16:44",
        "history": [
            hist("quote", "Sara Okafor", "Buyer", "Quote Q-2204 accepted - $4,720"),
            hist("artwork", "Mara Ivers", "Studio", "Dieline K-8 wrapped - foil layer split"),
            hist("approval", "Sara Okafor", "Buyer", "Approved v1"),
            hist("payment", "Sara Okafor", "Buyer", "$4,720 moved into Printy Custody"),
        ],
        "feed": [{"at": "Tue - 09:00", "who": "Printy SLA", "text": "production assignment breached 24h SLA - escalated", "jobCode": "PTY-1044"}],
    },
    {
        "id": "j5",
        "code": "PTY-1045",
        "title": "Lumen Learning - Workbooks",
        "product": "PUR workbook - 128pp",
        "qty": 3000,
        "value": 4110,
        "buyerId": "b-tomas",
        "buyerName": "Tomas Lind",
        "buyerCompany": "Lumen Learning",
        "managerId": "m-peter",
        "printerId": "p-kobo",
        "specs": {"material": "90gsm uncoated - 300gsm cover", "colors": "1c text - CMYK cover", "finish": "PUR bound - trimmed", "size": "A4 - 128pp"},
        "proofImg": None,
        "status": "on-track",
        "custody": "held",
        "stage": "delivery",
        "press": None,
        "progress": None,
        "owner": {"name": "Marta K. - SwiftLine", "role": "Courier", "action": "Deliver to Lumen HQ - dock 4 - 18 pallets", "waitingHrs": 5, "slaHrs": 12},
        "eta": "Today - 16:00",
        "placedAt": "Thu 07 Nov - 11:00",
        "history": [
            hist("quote", "Tomas Lind", "Buyer", "Quote Q-2190 accepted - $4,110"),
            hist("artwork", "Studio Ost", "Studio", "128pp imposed 16pp signatures"),
            hist("approval", "Tomas Lind", "Buyer", "Approved v2"),
            hist("payment", "Tomas Lind", "Buyer", "$4,110 moved into Printy Custody"),
            hist("production", "Peter Thiel", "Manager", "Assigned Kobo Bindery - accepted 13:05"),
            hist("printing", "Ren Sato", "Printer", "3,000 blocks printed - 2 shifts"),
            hist("finishing", "Ren Sato", "Printer", "PUR bound - 3-knife trimmed"),
            hist("qc", "Ren Sato", "Printer", "Passed - pull-test 8.2N - zero miscollations"),
        ],
        "feed": [{"at": "Today - 06:32", "who": "Marta K.", "text": "collected 18 pallets - ETA dock 4 by 16:00", "jobCode": "PTY-1045"}],
    },
    {
        "id": "j6",
        "code": "PTY-1046",
        "title": "Verve Fitness - Launch Flyers",
        "product": "A5 flyer - gloss",
        "qty": 10000,
        "value": 890,
        "buyerId": "b-nadia",
        "buyerName": "Nadia Petrova",
        "buyerCompany": "Verve Fitness",
        "managerId": "m-dale",
        "printerId": "p-halftone",
        "specs": {"material": "130gsm gloss", "colors": "CMYK - brand magenta critical", "finish": "Trim and band 250s", "size": "A5"},
        "proofImg": None,
        "status": "disputed",
        "custody": "held",
        "dispute": {"reason": "Buyer flagged colour shift on brand magenta - reprint or refund requested", "openedBy": "Nadia Petrova - Verve Fitness", "at": "Wed 13 Nov - 18:22", "amount": 890, "resolved": False},
        "stage": "finishing",
        "press": "hold",
        "progress": None,
        "owner": {"name": "Dale Carnegie", "role": "Manager", "action": "Resolve colour dispute with Halftone Works", "waitingHrs": 41, "slaHrs": 12},
        "eta": "On hold",
        "placedAt": "Sat 09 Nov - 10:11",
        "history": [
            hist("quote", "Nadia Petrova", "Buyer", "Quote Q-2194 accepted - $890"),
            hist("artwork", "Mara Ivers", "Studio", "Brand magenta locked - GRACoL profile"),
            hist("approval", "Nadia Petrova", "Buyer", "Approved v1"),
            hist("payment", "Nadia Petrova", "Buyer", "$890 moved into Printy Custody"),
            hist("production", "Dale Carnegie", "Manager", "Assigned Halftone Works - accepted 15:12"),
            hist("printing", "Iris Kohler", "Printer", "10,000 flyers printed on Indigo"),
        ],
        "feed": [{"at": "Wed - 18:22", "who": "Nadia Petrova", "text": "opened dispute - magenta shifted on trim batch 3", "jobCode": "PTY-1046"}],
    },
    {
        "id": "j7",
        "code": "PTY-1047",
        "title": "Field Notes - Zine No. 9",
        "product": "Perfect-bound zine - 64pp",
        "qty": 2500,
        "value": 1980,
        "buyerId": "b-ravi",
        "buyerName": "Ravi Anand",
        "buyerCompany": "Field Notes Mag",
        "managerId": "m-robert",
        "printerId": "p-kobo",
        "specs": {"material": "100gsm recycled", "colors": "2c + CMYK cover", "finish": "Perfect bound", "size": "170x240 mm"},
        "proofImg": None,
        "status": "completed",
        "custody": "released",
        "stage": "completed",
        "press": None,
        "progress": None,
        "owner": {"name": "Printy Custody", "role": "Escrow", "action": "Funds released - job archived", "waitingHrs": 0, "slaHrs": 0},
        "eta": "Delivered Tue 12 Nov",
        "placedAt": "Fri 01 Nov - 09:00",
        "history": [
            hist("quote", "Ravi Anand", "Buyer", "Quote Q-2155 accepted - $1,980"),
            hist("artwork", "Studio Ost", "Studio", "64pp - cover foil split"),
            hist("approval", "Ravi Anand", "Buyer", "Approved v1"),
            hist("payment", "Ravi Anand", "Buyer", "$1,980 moved into Printy Custody"),
            hist("production", "Robert Cialdini", "Manager", "Assigned Kobo Bindery - accepted 12:40"),
            hist("printing", "Ren Sato", "Printer", "2,500 blocks - night shift"),
            hist("finishing", "Ren Sato", "Printer", "Bound and trimmed 170x240"),
            hist("qc", "Ren Sato", "Printer", "Passed - sample pull clean"),
            hist("delivery", "Marta K.", "Courier", "Signed at Field Notes studio"),
            hist("completed", "Printy Custody", "Escrow", "Released $1,980 to Kobo Bindery"),
        ],
        "feed": [],
    },
]


def managers_as_records():
    """MANAGERS in seed / model column mapping."""
    return MANAGERS


def printers_as_records():
    """PRINTERS in seed / model column mapping."""
    return PRINTERS