# Generated by Django 5.2.11 on 2026-04-12 19:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FREE', 'Free'), ('BIASHARA', 'Biashara'), ('BIASHARA_PLUS', 'Biashara Plus'), ('BIASHARA_MAX', 'Biashara Max')], db_index=True, max_length=30, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='monthly price (KES)')),
                ('price_annual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='annual price (KES)')),
                ('currency', models.CharField(default='KES', max_length=3, verbose_name='currency')),
                ('shops_limit', models.PositiveSmallIntegerField(default=1, verbose_name='shops limit')),
                ('machines_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='machines limit')),
                ('products_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='products limit')),
                ('quotes_per_month_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='quotes per month limit')),
                ('users_limit', models.PositiveSmallIntegerField(default=1, verbose_name='users limit')),
                ('all_papers_enabled', models.BooleanField(default=True, verbose_name='all papers enabled')),
                ('branded_quotes_enabled', models.BooleanField(default=False, verbose_name='branded quotes enabled')),
                ('customer_history_enabled', models.BooleanField(default=False, verbose_name='customer history enabled')),
                ('analytics_level', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='basic', max_length=20, verbose_name='analytics level')),
                ('priority_support', models.BooleanField(default=False, verbose_name='priority support')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('public_tagline', models.CharField(blank=True, default='', max_length=120, verbose_name='public tagline')),
                ('best_for', models.CharField(blank=True, default='', max_length=200, verbose_name='best for')),
                ('benefits', models.JSONField(default=list, verbose_name='benefits')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('activation', 'Activation'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('manual_retry', 'Manual retry')], max_length=20, verbose_name='transaction type')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa')], default='mpesa', max_length=20, verbose_name='provider')),
                ('provider_method', models.CharField(choices=[('stk_push', 'STK Push'), ('ratiba', 'Ratiba'), ('manual_admin', 'Manual (Admin)')], default='stk_push', max_length=20, verbose_name='provider method')),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='merchant request ID')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='checkout request ID')),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='M-Pesa receipt number')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='phone number')),
                ('account_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='account reference')),
                ('transaction_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='transaction description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='KES', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed out')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('result_code', models.CharField(blank=True, default='', max_length=10, verbose_name='result code')),
                ('result_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='result description')),
                ('raw_request', models.JSONField(blank=True, null=True, verbose_name='raw STK request')),
                ('raw_callback', models.JSONField(blank=True, null=True, verbose_name='raw callback payload')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='initiated at')),
                ('callback_received_at', models.DateTimeField(blank=True, null=True, verbose_name='callback received at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate processing.', max_length=100, unique=True, verbose_name='idempotency key')),
                ('external_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='external reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_transactions', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='shops.shop', verbose_name='shop')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10, verbose_name='billing interval')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('grace_period', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
                ('renews_at', models.DateTimeField(blank=True, null=True, verbose_name='renews at')),
                ('auto_renew_enabled', models.BooleanField(default=True, verbose_name='auto renew enabled')),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='grace period ends at')),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='cancellation requested at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='suspended at')),
                ('last_renewal_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last renewal attempt at')),
                ('next_renewal_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='next renewal attempt at')),
                ('payment_phone_e164', models.CharField(blank=True, default='', max_length=20, verbose_name='payment phone (E.164)')),
                ('mpesa_reference_last', models.CharField(blank=True, default='', max_length=100, verbose_name='last M-Pesa reference')),
                ('over_limit', models.BooleanField(default=False, verbose_name='over limit')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'shop subscription',
                'verbose_name_plural': 'shop subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(verbose_name='due at')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='attempted at')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('initiated', 'Initiated'), ('awaiting_callback', 'Awaiting callback'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='queued', max_length=20, verbose_name='status')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='attempt number')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='failure reason')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='next retry at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_attempts', to='billing.paymenttransaction', verbose_name='payment transaction')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_attempts', to='billing.shopsubscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'renewal attempt',
                'verbose_name_plural': 'renewal attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.shopsubscription', verbose_name='subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription_shops', to='shops.shop', verbose_name='shop')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_shops', to='billing.shopsubscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'subscription shop',
                'verbose_name_plural': 'subscription shops',
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this counter covers.', verbose_name='month')),
                ('quotes_created_count', models.PositiveIntegerField(default=0, verbose_name='quotes created')),
                ('active_products_count_snapshot', models.PositiveIntegerField(default=0, verbose_name='active products snapshot')),
                ('active_users_count_snapshot', models.PositiveIntegerField(default=0, verbose_name='active users snapshot')),
                ('active_machines_count_snapshot', models.PositiveIntegerField(default=0, verbose_name='active machines snapshot')),
                ('shops_count_snapshot', models.PositiveIntegerField(default=0, verbose_name='shops snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_counters', to='billing.shopsubscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'usage counter',
                'verbose_name_plural': 'usage counters',
                'ordering': ['-month'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['checkout_request_id'], name='billing_txn_checkout_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant_request_id'], name='billing_txn_merchant_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['mpesa_receipt_number'], name='billing_txn_receipt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionshop',
            unique_together={('subscription', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='usagecounter',
            unique_together={('owner', 'month')},
        ),
    ]
