# Generated by Django 5.2.11 on 2026-04-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymenttransaction_response_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('activation', 'Activation'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('manual_retry', 'Manual retry'), ('sandbox_test', 'Sandbox test')], max_length=20, verbose_name='transaction type'),
        ),
    ]
