# Generated by Django 5.2.11 on 2026-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_paymenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs Review')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
    ]
