# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('file', models.FileField(blank=True, null=True, upload_to='managed_jobs/%Y/%m/', verbose_name='file')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(choices=[('artwork', 'Artwork'), ('customer_upload', 'Customer upload'), ('broker_revision', 'Broker revision'), ('proof', 'Proof'), ('print_ready', 'Print ready'), ('delivery_evidence', 'Delivery evidence')], default='customer_upload', max_length=32, verbose_name='file type')),
                ('visibility', models.CharField(choices=[('client', 'Client'), ('partner', 'Partner'), ('shop', 'Shop'), ('ops', 'Ops'), ('internal', 'Internal')], default='client', max_length=16, verbose_name='visibility')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('manager_review', 'Manager review'), ('manager_approved', 'Manager approved'), ('manager_rejected', 'Manager rejected'), ('proof_uploaded', 'Proof uploaded'), ('proof_approved', 'Proof approved'), ('proof_rejected', 'Proof rejected'), ('revision_requested', 'Revision requested'), ('print_ready', 'Print ready'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('replaced', 'Replaced')], default='uploaded', max_length=32, verbose_name='status')),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'job file',
                'verbose_name_plural': 'job files',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('event_type', models.CharField(max_length=64, verbose_name='event type')),
                ('summary', models.CharField(blank=True, default='', max_length=255, verbose_name='summary')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'managed job event',
                'verbose_name_plural': 'managed job events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManagedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('managed_reference', models.CharField(blank=True, default='', help_text='Stable reference for the managed operational job.', max_length=50, unique=True, verbose_name='managed reference')),
                ('title', models.CharField(blank=True, default='', help_text='Operational label for the managed job.', max_length=255, verbose_name='title')),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public tracking token for managed job status links.', unique=True, verbose_name='tracking token')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('quoted', 'Quoted'), ('awaiting_payment', 'Awaiting payment'), ('payment_confirmed', 'Payment confirmed'), ('assigned', 'Assigned'), ('in_production', 'In production'), ('finishing', 'Finishing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=32, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmation_pending', 'Confirmation pending'), ('confirmed', 'Confirmed'), ('release_ready', 'Release ready'), ('payout_on_hold', 'Payout on hold'), ('released', 'Released'), ('refunded', 'Refunded')], default='pending', max_length=32, verbose_name='payment status')),
                ('assignment_status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assignment_pending', 'Assignment pending'), ('assigned', 'Assigned'), ('reassignment_required', 'Reassignment required'), ('overflow_review', 'Overflow review')], default='unassigned', max_length=32, verbose_name='assignment status')),
                ('exception_status', models.CharField(choices=[('clear', 'Clear'), ('production_issue', 'Production issue'), ('delivery_issue', 'Delivery issue'), ('dispute_open', 'Dispute open'), ('ops_review', 'Ops review')], default='clear', max_length=32, verbose_name='exception status')),
                ('fulfillment_mode', models.CharField(choices=[('printy_rider', 'Printy rider'), ('own_rider', 'Own rider'), ('pickup', 'Pickup')], default='pickup', max_length=32, verbose_name='fulfillment mode')),
                ('topology_type', models.CharField(choices=[('client_partner', 'Client to partner'), ('client_printy_support', 'Client to Printy support'), ('partner_shop', 'Partner to shop'), ('shop_ops', 'Shop to ops'), ('ops_internal', 'Ops internal')], default='client_printy_support', max_length=32, verbose_name='topology type')),
                ('urgency_type', models.CharField(choices=[('standard', 'Standard'), ('same_day', 'Same-day'), ('express', 'Express'), ('after_hours', 'After-hours'), ('emergency', 'Emergency')], default='standard', max_length=32, verbose_name='urgency type')),
                ('urgency_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('urgency_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('after_hours_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requested_deadline', models.DateTimeField(blank=True, null=True)),
                ('requested_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('operational_priority_level', models.PositiveSmallIntegerField(default=1)),
                ('client_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('printy_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('broker_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payout_hold', models.BooleanField(default=False)),
                ('artwork_required', models.BooleanField(default=False)),
                ('artwork_reminder_sent', models.BooleanField(default=False)),
                ('dispute_open', models.BooleanField(default=False)),
                ('production_issue_flag', models.BooleanField(default=False)),
                ('delivery_issue_flag', models.BooleanField(default=False)),
                ('ops_review_required', models.BooleanField(default=False)),
                ('operational_snapshot', models.JSONField(blank=True, default=dict)),
                ('workflow_metadata', models.JSONField(blank=True, default=dict)),
                ('relationship_snapshot', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('production_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'managed job',
                'verbose_name_plural': 'managed jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedJobPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('recipient_role', models.CharField(choices=[('manager', 'Manager'), ('shop', 'Shop')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('release_reference', models.CharField(blank=True, default='', max_length=100)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'managed job payout',
                'verbose_name_plural': 'managed job payouts',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_production', 'In production'), ('finishing', 'Finishing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned')], default='pending', max_length=32, verbose_name='status')),
                ('shop_payout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('urgency_type', models.CharField(choices=[('standard', 'Standard'), ('same_day', 'Same-day'), ('express', 'Express'), ('after_hours', 'After-hours'), ('emergency', 'Emergency')], default='standard', max_length=32, verbose_name='urgency type')),
                ('operational_priority_level', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('requested_deadline', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_notes', models.TextField(blank=True, default='')),
                ('operational_snapshot', models.JSONField(blank=True, default=dict)),
                ('assigned_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to='shops.shop', verbose_name='assigned shop')),
            ],
            options={
                'verbose_name': 'job assignment',
                'verbose_name_plural': 'job assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
