# Generated by Django 5.2.11 on 2026-03-04 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('title', models.CharField(help_text='Short title for the job.', max_length=255, verbose_name='title')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Job specifications (product, quantity, paper, etc.).', verbose_name='specs')),
                ('location', models.CharField(blank=True, default='', help_text='Location or area for the job.', max_length=255, verbose_name='location')),
                ('deadline', models.DateTimeField(blank=True, help_text='When the job needs to be done.', null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='status')),
                ('public_token', models.CharField(blank=True, db_index=True, help_text='Un-guessable token for public share URL.', max_length=64, unique=True, verbose_name='public token')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'job request',
                'verbose_name_plural': 'job requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('price_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price the claimant offers.', max_digits=12, null=True, verbose_name='price offered')),
                ('message', models.TextField(blank=True, default='', help_text='Message from the claimant.', verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_claims', to=settings.AUTH_USER_MODEL, verbose_name='claimed by')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='jobs.jobrequest', verbose_name='job request')),
            ],
            options={
                'verbose_name': 'job claim',
                'verbose_name_plural': 'job claims',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('job_request', 'claimed_by'), name='unique_job_claim')],
            },
        ),
    ]
