# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('price_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price the claimant offers.', max_digits=12, null=True, verbose_name='price offered')),
                ('message', models.TextField(blank=True, default='', help_text='Message from the claimant.', verbose_name='message')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_claims', to=settings.AUTH_USER_MODEL, verbose_name='claimed by')),
            ],
            options={
                'verbose_name': 'job claim',
                'verbose_name_plural': 'job claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('title', models.CharField(help_text='Short title for the job.', max_length=255, verbose_name='title')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Job specifications (product, quantity, paper, etc.).', verbose_name='specs')),
                ('location', models.CharField(blank=True, default='', help_text='Location or area for the job.', max_length=255, verbose_name='location')),
                ('deadline', models.DateTimeField(blank=True, help_text='When the job needs to be done.', null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='status')),
                ('public_token', models.CharField(blank=True, db_index=True, help_text='Un-guessable token for public share URL.', max_length=64, null=True, unique=True, verbose_name='public token')),
                ('machine_type', models.CharField(choices=[('DIGITAL', 'Digital'), ('LARGE_FORMAT', 'Large Format'), ('UV', 'UV'), ('OFFSET', 'Offset'), ('OTHER', 'Other')], default='DIGITAL', help_text='Required machine type (DIGITAL, LARGE_FORMAT, UV, etc).', max_length=30, verbose_name='machine type')),
                ('finishing_capabilities', models.JSONField(blank=True, default=list, help_text="List of finishing capabilities required (e.g. ['lamination', 'cutting']).", verbose_name='finishing capabilities needed')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'job request',
                'verbose_name_plural': 'job requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('message', models.TextField(default='', help_text='Notification message.', verbose_name='message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('job_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.jobclaim', verbose_name='job claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.jobrequest', verbose_name='job request')),
            ],
            options={
                'verbose_name': 'job notification',
                'verbose_name_plural': 'job notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobclaim',
            name='job_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='jobs.jobrequest', verbose_name='job request'),
        ),
        migrations.AddConstraint(
            model_name='jobclaim',
            constraint=models.UniqueConstraint(fields=('job_request', 'claimed_by'), name='unique_job_claim'),
        ),
    ]
