# Generated by Django 5.2.11 on 2026-03-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='public_token',
            field=models.CharField(blank=True, db_index=True, help_text='Un-guessable token for public share URL.', max_length=64, null=True, unique=True, verbose_name='public token'),
        ),
    ]
