# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('production', '0001_initial'),
        ('quotes', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassignment',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='reassigned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments', to='jobs.jobassignment', verbose_name='reassigned from'),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignments', to='quotes.quote', verbose_name='source shop quote'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_files', to='jobs.jobassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='jobs.jobfile', verbose_name='replaces'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='source_quote_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_files', to='quotes.quoteattachment', verbose_name='source shop quote attachment'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='source_quote_request_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_files', to='quotes.quoterequestattachment', verbose_name='source quote request attachment'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_job_files', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_status_events', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='jobs.jobassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='job_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='jobs.jobfile', verbose_name='job file'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='assigned_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='shops.shop', verbose_name='assigned shop'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_managed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='broker'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs_dispatched', to=settings.AUTH_USER_MODEL, verbose_name='dispatched by'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='source_production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='production.productionorder', verbose_name='source production order'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='quotes.quote', verbose_name='source shop quote'),
        ),
        migrations.AddField(
            model_name='managedjob',
            name='source_quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='quotes.quoterequest', verbose_name='source quote request'),
        ),
        migrations.AddField(
            model_name='jobstatusevent',
            name='managed_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.managedjob', verbose_name='managed job'),
        ),
        migrations.AddField(
            model_name='jobfile',
            name='managed_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_files', to='jobs.managedjob', verbose_name='managed job'),
        ),
        migrations.AddField(
            model_name='jobassignment',
            name='managed_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.managedjob', verbose_name='managed job'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='jobs.jobassignment', verbose_name='assignment'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='managed_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='jobs.managedjob', verbose_name='managed job'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_job_payouts', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_job_payouts_released', to=settings.AUTH_USER_MODEL, verbose_name='released by'),
        ),
        migrations.AddIndex(
            model_name='managedjob',
            index=models.Index(fields=['status', 'payment_status'], name='managed_job_status_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='managedjob',
            index=models.Index(fields=['assigned_shop', 'assignment_status'], name='managed_job_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='managedjob',
            index=models.Index(fields=['operational_priority_level', 'status'], name='managed_job_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatusevent',
            index=models.Index(fields=['managed_job', 'event_type'], name='job_status_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='jobstatusevent',
            index=models.Index(fields=['managed_job', '-created_at'], name='job_status_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfile',
            index=models.Index(fields=['managed_job', 'file_type'], name='job_file_type_idx'),
        ),
        migrations.AddIndex(
            model_name='jobfile',
            index=models.Index(fields=['managed_job', 'visibility'], name='job_file_visibility_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobfile',
            constraint=models.UniqueConstraint(condition=models.Q(('source_quote_request_attachment__isnull', False)), fields=('managed_job', 'source_quote_request_attachment'), name='unique_job_file_source_quote_attachment'),
        ),
        migrations.AddConstraint(
            model_name='jobfile',
            constraint=models.UniqueConstraint(condition=models.Q(('source_quote_attachment__isnull', False)), fields=('managed_job', 'source_quote_attachment'), name='unique_job_file_source_shop_attachment'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['assigned_shop', 'status'], name='job_assignment_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobassignment',
            index=models.Index(fields=['assigned_shop', 'operational_priority_level'], name='job_assignment_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('reassigned_from__isnull', True)), fields=('managed_job',), name='unique_active_assignment_per_managed_job'),
        ),
        migrations.AddIndex(
            model_name='managedjobpayout',
            index=models.Index(fields=['managed_job', 'status'], name='job_payout_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='managedjobpayout',
            index=models.Index(fields=['recipient', 'status'], name='job_payout_recipient_idx'),
        ),
        migrations.AddConstraint(
            model_name='managedjobpayout',
            constraint=models.UniqueConstraint(fields=('managed_job', 'recipient_role'), name='unique_payout_recipient_role_per_job'),
        ),
    ]
