# Generated by Django 5.2.11 on 2026-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedjobpayout',
            name='disbursement_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', help_text="How the money reached the recipient. 'manual' means an admin transferred it out of band.", max_length=16, verbose_name='disbursement mode'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name='failure reason'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw response from the payout provider, when one is involved.', verbose_name='provider response'),
        ),
        migrations.AddField(
            model_name='managedjobpayout',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', help_text='Bank/M-Pesa confirmation reference for a manual transfer, or the provider reference if automatic.', max_length=100, verbose_name='transfer reference'),
        ),
        migrations.AlterField(
            model_name='managedjobpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('released', 'Released'), ('failed', 'Failed'), ('on_hold', 'On hold'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
