# Generated by Django 5.2.11 on 2026-03-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_null_public_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='finishing_capabilities',
            field=models.JSONField(blank=True, default=list, help_text="List of finishing capabilities required (e.g. ['lamination', 'cutting']).", verbose_name='finishing capabilities needed'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='machine_type',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('LARGE_FORMAT', 'Large Format'), ('UV', 'UV'), ('OFFSET', 'Offset'), ('OTHER', 'Other')], default='DIGITAL', help_text='Required machine type (DIGITAL, LARGE_FORMAT, UV, etc).', max_length=30, verbose_name='machine type'),
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('message', models.TextField(default='', help_text='Notification message.', verbose_name='message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('job_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.jobclaim', verbose_name='job claim')),
                ('job_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='jobs.jobrequest', verbose_name='job request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'job notification',
                'verbose_name_plural': 'job notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
