# Generated by Django 5.2.11 on 2026-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_managed_job_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('proof_uploaded', 'Proof uploaded'), ('proof_approved', 'Proof approved'), ('proof_rejected', 'Proof rejected'), ('revision_requested', 'Revision requested'), ('print_ready', 'Print ready'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('replaced', 'Replaced')], default='uploaded', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='jobpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='jobsettlementsplit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='jobsettlementsplit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='managedjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='managedjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='managedjobevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='managedjobevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
    ]
