# Generated by Django 5.2.11 on 2026-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_jobpayment_mpesa_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpayment',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs Review')], default='pending', max_length=32, verbose_name='payment status'),
        ),
    ]
