# Generated by Django 5.2.11 on 2026-05-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_managedjob_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedjob',
            name='artwork_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_production', 'In production'), ('finishing', 'Finishing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reassigned', 'Reassigned')], default='pending', max_length=32, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='file_type',
            field=models.CharField(choices=[('artwork', 'Artwork'), ('customer_upload', 'Customer upload'), ('broker_revision', 'Broker revision'), ('proof', 'Proof'), ('print_ready', 'Print ready'), ('delivery_evidence', 'Delivery evidence')], default='customer_upload', max_length=32, verbose_name='file type'),
        ),
    ]
