# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityPricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('min_sheets', models.PositiveIntegerField()),
                ('max_sheets', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimum_order_floor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'quantity pricing tier',
                'verbose_name_plural': 'quantity pricing tiers',
                'ordering': ['min_sheets', 'max_sheets'],
            },
        ),
        migrations.CreateModel(
            name='SetupCostPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Setup Cost Policy', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('setup_minutes', models.PositiveIntegerField(default=10)),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=12)),
                ('machine_setup_fee', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=12)),
                ('admin_handling_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
                ('file_check_fee', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'setup cost policy',
                'verbose_name_plural': 'setup cost policies',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WastePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Waste Policy', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('fixed_waste_sheets', models.PositiveIntegerField(default=2)),
                ('variable_waste_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1000'), max_digits=6)),
                ('minimum_billable_sheets', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'waste policy',
                'verbose_name_plural': 'waste policies',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(default='', help_text='Display name of the finishing service.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Stable frontend/backend key for this finishing rule.', max_length=255, verbose_name='slug')),
                ('thickness_microns', models.PositiveIntegerField(blank=True, help_text='Lamination thickness in microns (e.g. 12, 25, 50).', null=True, verbose_name='thickness (µm)')),
                ('is_single_sided_only', models.BooleanField(default=False, help_text='If true, this finishing can only be applied to one side.', verbose_name='one-side only')),
                ('charge_unit', models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_SIDE', 'Per Side'), ('PER_SHEET', 'Per Sheet'), ('PER_SIDE_PER_SHEET', 'Per Side Per Sheet (Legacy)'), ('PER_SQM', 'Per Square Meter'), ('FLAT', 'Flat')], default='PER_PIECE', help_text='How this finishing is charged. For lamination, use per sheet.', max_length=20, verbose_name='charge unit')),
                ('billing_basis', models.CharField(choices=[('per_sheet', 'Per Sheet'), ('per_piece', 'Per Piece'), ('flat_per_job', 'Flat Per Job'), ('flat_per_group', 'Flat Per Group'), ('flat_per_line', 'Flat Per Line')], default='per_piece', help_text='Billing basis used by pricing. For lamination, use per sheet.', max_length=30, verbose_name='billing basis')),
                ('side_mode', models.CharField(choices=[('ignore_sides', 'Ignore Sides'), ('per_selected_side', 'Per Selected Side')], default='ignore_sides', help_text='Whether the rate changes based on one side or both sides.', max_length=30, verbose_name='side mode')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base rate. For lamination, this is the one-side rate per sheet.', max_digits=12, verbose_name='price')),
                ('double_side_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional rate when lamination is applied to both sides. Leave blank to use 2× the one-side rate.', max_digits=12, null=True, verbose_name='both-side rate')),
                ('setup_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Optional one-time setup fee.', max_digits=12, null=True, verbose_name='setup fee')),
                ('min_qty', models.PositiveIntegerField(blank=True, help_text='Minimum quantity for this rate.', null=True, verbose_name='min quantity')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum charge after rule calculation.', max_digits=12, null=True, verbose_name='minimum charge')),
                ('applies_to_product_types', models.JSONField(blank=True, help_text='Optional list of product/category/pricing mode keys.', null=True, verbose_name='applies to product types')),
                ('display_unit_label', models.CharField(blank=True, default='', help_text="Optional UI label like 'per sheet'.", max_length=100, verbose_name='display unit label')),
                ('help_text', models.TextField(blank=True, default='', help_text='Optional customer-facing pricing explanation.', verbose_name='help text')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is active.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this finishing rate.', on_delete=django.db.models.deletion.CASCADE, related_name='finishing_rates', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'finishing rate',
                'verbose_name_plural': 'finishing rates',
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Printy Fee Policy', max_length=120)),
                ('policy_version', models.CharField(default='printy-fees-v1', max_length=40)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('under_production_threshold', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=12)),
                ('under_production_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=5)),
                ('standard_production_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5)),
                ('standard_markup_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), max_digits=5)),
                ('high_markup_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.8000'), max_digits=5)),
                ('high_markup_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=5)),
                ('high_production_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('high_production_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.3000'), max_digits=5)),
                ('high_production_markup_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), max_digits=5)),
                ('maximum_manager_markup_multiple', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('printer_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), editable=False, help_text='DEPRECATED historical field. Active quote pricing must not read this value.', max_digits=5)),
                ('broker_margin_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.2000'), editable=False, help_text='DEPRECATED historical field. Active quote pricing must not read this value.', max_digits=5)),
                ('small_job_limit', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=12)),
                ('medium_job_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('small_job_max_multiple', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5)),
                ('medium_job_max_multiple', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('bulk_job_max_multiple', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('add_platform_fee_on_top', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'platform fee policy',
                'verbose_name_plural': 'platform fee policies',
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_platform_fee_policy')],
            },
        ),
        migrations.CreateModel(
            name='ShopPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these pricing settings are active.', verbose_name='is active')),
                ('shop', models.OneToOneField(help_text='Shop that owns these marketplace pricing settings.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'shop pricing settings',
                'verbose_name_plural': 'shop pricing settings',
                'ordering': ['shop__name'],
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name (e.g. Bulk 500+, High Volume).', max_length=255, verbose_name='name')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to qualify for this discount.', verbose_name='min quantity')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10% off).', max_digits=5, verbose_name='discount percent')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount is available.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this discount.', on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['shop', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='PrintingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('CUSTOM', 'Custom')], default='A4', help_text='Sheet size this rate applies to.', max_length=20, verbose_name='sheet size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='BW', help_text='Black & white or color printing.', max_length=10, verbose_name='color mode')),
                ('single_price', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Base print charge per side. Simplex uses this once; duplex uses it twice.', max_digits=12, verbose_name='single price')),
                ('double_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional duplex-per-sheet override. Leave blank to calculate from per-side price plus any duplex surcharge.', max_digits=12, null=True, verbose_name='double price')),
                ('duplex_surcharge', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Optional flat surcharge added once per duplex sheet when the surcharge rule applies.', max_digits=12, verbose_name='duplex surcharge')),
                ('duplex_surcharge_enabled', models.BooleanField(default=False, help_text='Turn on duplex surcharge logic for this printing rate.', verbose_name='duplex surcharge enabled')),
                ('duplex_surcharge_min_gsm', models.PositiveIntegerField(blank=True, help_text='Optional gsm threshold. The duplex surcharge only applies when the selected paper gsm meets or exceeds this value.', null=True, verbose_name='duplex surcharge min gsm')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is active.', verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this rate as the main rate for the price list when no specific rate is specified. One default per machine.', verbose_name='is default')),
                ('machine', models.ForeignKey(help_text='Machine this rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='printing_rates', to='inventory.machine', verbose_name='machine')),
            ],
            options={
                'verbose_name': 'printing rate',
                'verbose_name_plural': 'printing rates',
                'ordering': ['machine', 'sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'sheet_size', 'color_mode'), name='unique_machine_sheet_color'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('machine',), name='unique_machine_default_printing_rate')],
            },
        ),
    ]
