# Generated by Django 5.2.11 on 2026-04-05 21:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Category name, e.g. Lamination, Binding.', max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this category.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'finishing category',
                'verbose_name_plural': 'finishing categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(default='', help_text='Display name of the finishing service.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, default='', help_text='Stable frontend/backend key for this finishing rule.', max_length=255, verbose_name='slug')),
                ('thickness_microns', models.PositiveIntegerField(blank=True, help_text='Lamination thickness in microns (e.g. 12, 25, 50).', null=True, verbose_name='thickness (µm)')),
                ('is_single_sided_only', models.BooleanField(default=False, help_text='If true, this finishing can only be applied to one side.', verbose_name='one-side only')),
                ('charge_unit', models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_SIDE', 'Per Side'), ('PER_SHEET', 'Per Sheet'), ('PER_SIDE_PER_SHEET', 'Per Side Per Sheet (Legacy)'), ('PER_SQM', 'Per Square Meter'), ('FLAT', 'Flat')], default='PER_PIECE', help_text='How this finishing is charged. For lamination, use per sheet.', max_length=20, verbose_name='charge unit')),
                ('billing_basis', models.CharField(choices=[('per_sheet', 'Per Sheet'), ('per_piece', 'Per Piece'), ('flat_per_job', 'Flat Per Job'), ('flat_per_group', 'Flat Per Group'), ('flat_per_line', 'Flat Per Line')], default='per_piece', help_text='Billing basis used by pricing. For lamination, use per sheet.', max_length=30, verbose_name='billing basis')),
                ('side_mode', models.CharField(choices=[('ignore_sides', 'Ignore Sides'), ('per_selected_side', 'Per Selected Side')], default='ignore_sides', help_text='Whether the rate changes based on one side or both sides.', max_length=30, verbose_name='side mode')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base rate. For lamination, this is the one-side rate per sheet.', max_digits=12, verbose_name='price')),
                ('double_side_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional rate when lamination is applied to both sides. Leave blank to use 2× the one-side rate.', max_digits=12, null=True, verbose_name='both-side rate')),
                ('setup_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Optional one-time setup fee.', max_digits=12, null=True, verbose_name='setup fee')),
                ('min_qty', models.PositiveIntegerField(blank=True, help_text='Minimum quantity for this rate.', null=True, verbose_name='min quantity')),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum charge after rule calculation.', max_digits=12, null=True, verbose_name='minimum charge')),
                ('applies_to_product_types', models.JSONField(blank=True, help_text='Optional list of product/category/pricing mode keys.', null=True, verbose_name='applies to product types')),
                ('display_unit_label', models.CharField(blank=True, default='', help_text="Optional UI label like 'per sheet'.", max_length=100, verbose_name='display unit label')),
                ('help_text', models.TextField(blank=True, default='', help_text='Optional customer-facing pricing explanation.', verbose_name='help text')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is active.', verbose_name='is active')),
                ('category', models.ForeignKey(blank=True, help_text='Finishing category (e.g. Lamination, Binding).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_rates', to='pricing.finishingcategory', verbose_name='category')),
                ('shop', models.ForeignKey(help_text='Shop that owns this finishing rate.', on_delete=django.db.models.deletion.CASCADE, related_name='finishing_rates', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'finishing rate',
                'verbose_name_plural': 'finishing rates',
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('material_type', models.CharField(default='', help_text='Type of material (e.g. vinyl, banner).', max_length=255, verbose_name='material type')),
                ('unit', models.CharField(default='SQM', help_text='Unit of measure (e.g. SQM for square meters).', max_length=20, verbose_name='unit')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit.', max_digits=12, verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit.', max_digits=12, verbose_name='selling price')),
                ('print_price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional area-based print charge per square meter for large-format work.', max_digits=12, verbose_name='print price per sqm')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this material is active.', verbose_name='is active')),
                ('production_size', models.ForeignKey(blank=True, help_text='Optional default parent sheet size for roll/sheet materials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.productionpapersize', verbose_name='production size')),
                ('shop', models.ForeignKey(help_text='Shop that owns this material.', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['shop', 'material_type'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('code', models.CharField(choices=[('DESIGN', 'Design'), ('DELIVERY', 'Delivery'), ('RUSH', 'Rush / Urgent'), ('SETUP', 'Setup')], default='DESIGN', help_text='Service code (DESIGN, DELIVERY, RUSH, SETUP).', max_length=30, verbose_name='code')),
                ('name', models.CharField(default='', help_text='Display name (e.g. Design Charges, Delivery).', max_length=255, verbose_name='name')),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Fixed price'), ('TIERED_DISTANCE', 'Distance-based tiers')], default='FIXED', help_text='FIXED or TIERED_DISTANCE.', max_length=30, verbose_name='pricing type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price when pricing_type=FIXED.', max_digits=12, null=True, verbose_name='price')),
                ('is_optional', models.BooleanField(default=True, help_text='Client can choose to add or skip.', verbose_name='is optional')),
                ('is_negotiable', models.BooleanField(default=False, help_text='Seller can override price (e.g. design).', verbose_name='is negotiable')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is available.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this service rate.', on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'service rate',
                'verbose_name_plural': 'service rates',
                'ordering': ['shop', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('min_km', models.DecimalField(decimal_places=2, help_text='Minimum distance in km.', max_digits=12, verbose_name='min km')),
                ('max_km', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum distance in km. Null = and above.', max_digits=12, null=True, verbose_name='max km')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this tier.', max_digits=12, verbose_name='price')),
                ('service_rate', models.ForeignKey(help_text='Service rate this tier belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.servicerate', verbose_name='service rate')),
            ],
            options={
                'verbose_name': 'service rate tier',
                'verbose_name_plural': 'service rate tiers',
                'ordering': ['service_rate', 'min_km'],
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name (e.g. Bulk 500+, High Volume).', max_length=255, verbose_name='name')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to qualify for this discount.', verbose_name='min quantity')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10% off).', max_digits=5, verbose_name='discount percent')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount is available.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this discount.', on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['shop', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='PrintingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('CUSTOM', 'Custom')], default='A4', help_text='Sheet size this rate applies to.', max_length=20, verbose_name='sheet size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='BW', help_text='Black & white or color printing.', max_length=10, verbose_name='color mode')),
                ('single_price', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Base print charge per side. Simplex uses this once; duplex uses it twice.', max_digits=12, verbose_name='single price')),
                ('double_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional duplex-per-sheet override. Leave blank to calculate from per-side price plus any duplex surcharge.', max_digits=12, null=True, verbose_name='double price')),
                ('duplex_surcharge', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Optional flat surcharge added once per duplex sheet when the surcharge rule applies.', max_digits=12, verbose_name='duplex surcharge')),
                ('duplex_surcharge_enabled', models.BooleanField(default=False, help_text='Turn on duplex surcharge logic for this printing rate.', verbose_name='duplex surcharge enabled')),
                ('duplex_surcharge_min_gsm', models.PositiveIntegerField(blank=True, help_text='Optional gsm threshold. The duplex surcharge only applies when the selected paper gsm meets or exceeds this value.', null=True, verbose_name='duplex surcharge min gsm')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is active.', verbose_name='is active')),
                ('is_default', models.BooleanField(default=False, help_text='Use this rate as the main rate for the price list when no specific rate is specified. One default per machine.', verbose_name='is default')),
                ('machine', models.ForeignKey(help_text='Machine this rate applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='printing_rates', to='inventory.machine', verbose_name='machine')),
            ],
            options={
                'verbose_name': 'printing rate',
                'verbose_name_plural': 'printing rates',
                'ordering': ['machine', 'sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('machine', 'sheet_size', 'color_mode'), name='unique_machine_sheet_color'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('machine',), name='unique_machine_default_printing_rate')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicerate',
            constraint=models.UniqueConstraint(fields=('shop', 'code'), name='unique_shop_service_code'),
        ),
    ]
