# Generated by Django 5.2.11 on 2026-05-18 19:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('shops', '0004_shop_mvp_rate_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('broker_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Marketplace broker margin percentage added to the shop base price.', max_digits=5, verbose_name='broker margin percent')),
                ('service_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Printy service margin percentage added to the shop base price.', max_digits=5, verbose_name='service margin percent')),
                ('broker_margin_locked', models.BooleanField(default=True, help_text='Whether the broker margin is locked for standard shop users.', verbose_name='broker margin locked')),
                ('service_margin_locked', models.BooleanField(default=True, help_text='Whether the Printy service margin is locked for standard shop users.', verbose_name='service margin locked')),
                ('is_active', models.BooleanField(default=True, help_text='Whether these pricing settings are active.', verbose_name='is active')),
                ('shop', models.OneToOneField(help_text='Shop that owns these marketplace pricing settings.', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'shop pricing settings',
                'verbose_name_plural': 'shop pricing settings',
                'ordering': ['shop__name'],
            },
        ),
    ]
