# Generated by Django 5.2.11 on 2026-03-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_paper_is_default'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingrate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this rate as the main rate for the price list when no specific rate is specified. One default per machine.', verbose_name='is default'),
        ),
        migrations.AddConstraint(
            model_name='printingrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('machine',), name='unique_machine_default_printing_rate'),
        ),
    ]
