# Generated by Django 5.2.11 on 2026-03-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Category name, e.g. Lamination, Binding.', max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this category.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'finishing category',
                'verbose_name_plural': 'finishing categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Finishing category (e.g. Lamination, Binding).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_rates', to='pricing.finishingcategory', verbose_name='category'),
        ),
    ]
