# Generated by Django 5.2.11 on 2026-03-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_add_printing_rate_is_default'),
        ('shops', '0003_shop_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name (e.g. Bulk 500+, High Volume).', max_length=255, verbose_name='name')),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity to qualify for this discount.', verbose_name='min quantity')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10% off).', max_digits=5, verbose_name='discount percent')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this discount is available.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this discount.', on_delete=django.db.models.deletion.CASCADE, related_name='volume_discounts', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'volume discount',
                'verbose_name_plural': 'volume discounts',
                'ordering': ['shop', 'min_quantity'],
            },
        ),
    ]
