# Generated by Django 5.2.11 on 2026-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_seed_finishing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='lead_in_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Blank roll margin before the first printed row in mm. Added to consumed roll length and therefore to billable area. Null = 0.', null=True, verbose_name='lead-in (mm)'),
        ),
        migrations.AddField(
            model_name='material',
            name='lead_out_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Blank roll margin after the last printed row in mm. Added to consumed roll length and therefore to billable area. Null = 0.', null=True, verbose_name='lead-out (mm)'),
        ),
    ]
