# Generated by Django 5.2.11 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_add_volume_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishingrate',
            name='charge_unit',
            field=models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_SIDE', 'Per Side'), ('PER_SHEET', 'Per Sheet'), ('PER_SIDE_PER_SHEET', 'Per Side Per Sheet'), ('PER_SQM', 'Per Square Meter'), ('FLAT', 'Flat')], default='PER_PIECE', help_text='How this finishing is charged (per piece, per side, per sqm, flat).', max_length=20, verbose_name='charge unit'),
        ),
    ]
