# Generated by Django 5.2.11 on 2026-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingrate',
            name='applies_to_product_types',
            field=models.JSONField(blank=True, help_text='Optional list of product/category/pricing mode keys.', null=True, verbose_name='applies to product types'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='billing_basis',
            field=models.CharField(choices=[('per_sheet', 'Per Sheet'), ('per_piece', 'Per Piece'), ('flat_per_job', 'Flat Per Job'), ('flat_per_group', 'Flat Per Group'), ('flat_per_line', 'Flat Per Line')], default='per_piece', help_text='Canonical billing basis used by the pricing engine.', max_length=30, verbose_name='billing basis'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='display_unit_label',
            field=models.CharField(blank=True, default='', help_text="Optional UI label like 'per sheet per side'.", max_length=100, verbose_name='display unit label'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='Optional frontend-facing pricing explanation.', verbose_name='help text'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='minimum_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional minimum charge after rule calculation.', max_digits=12, null=True, verbose_name='minimum charge'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='side_mode',
            field=models.CharField(choices=[('ignore_sides', 'Ignore Sides'), ('per_selected_side', 'Per Selected Side')], default='ignore_sides', help_text='Whether rate multiplies by selected finishing sides.', max_length=30, verbose_name='side mode'),
        ),
        migrations.AddField(
            model_name='finishingrate',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Stable frontend/backend key for this finishing rule.', max_length=255, verbose_name='slug'),
        ),
    ]
