# Generated by Django 5.2.11 on 2026-04-02 04:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_finishingrate_applies_to_product_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingrate',
            name='duplex_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Optional flat surcharge added once per duplex sheet when the surcharge rule applies.', max_digits=12, verbose_name='duplex surcharge'),
        ),
        migrations.AddField(
            model_name='printingrate',
            name='duplex_surcharge_enabled',
            field=models.BooleanField(default=False, help_text='Turn on duplex surcharge logic for this printing rate.', verbose_name='duplex surcharge enabled'),
        ),
        migrations.AddField(
            model_name='printingrate',
            name='duplex_surcharge_min_gsm',
            field=models.PositiveIntegerField(blank=True, help_text='Optional gsm threshold. The duplex surcharge only applies when the selected paper gsm meets or exceeds this value.', null=True, verbose_name='duplex surcharge min gsm'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='billing_basis',
            field=models.CharField(choices=[('per_sheet', 'Per Sheet'), ('per_piece', 'Per Piece'), ('flat_per_job', 'Flat Per Job'), ('flat_per_group', 'Flat Per Group'), ('flat_per_line', 'Flat Per Line')], default='per_piece', help_text='Billing basis used by pricing. For lamination, use per sheet.', max_length=30, verbose_name='billing basis'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='charge_unit',
            field=models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_SIDE', 'Per Side'), ('PER_SHEET', 'Per Sheet'), ('PER_SIDE_PER_SHEET', 'Per Side Per Sheet (Legacy)'), ('PER_SQM', 'Per Square Meter'), ('FLAT', 'Flat')], default='PER_PIECE', help_text='How this finishing is charged. For lamination, use per sheet.', max_length=20, verbose_name='charge unit'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='display_unit_label',
            field=models.CharField(blank=True, default='', help_text="Optional UI label like 'per sheet'.", max_length=100, verbose_name='display unit label'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='double_side_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional rate when lamination is applied to both sides. Leave blank to use 2× the one-side rate.', max_digits=12, null=True, verbose_name='both-side rate'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='Optional customer-facing pricing explanation.', verbose_name='help text'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='is_single_sided_only',
            field=models.BooleanField(default=False, help_text='If true, this finishing can only be applied to one side.', verbose_name='one-side only'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base rate. For lamination, this is the one-side rate per sheet.', max_digits=12, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='finishingrate',
            name='side_mode',
            field=models.CharField(choices=[('ignore_sides', 'Ignore Sides'), ('per_selected_side', 'Per Selected Side')], default='ignore_sides', help_text='Whether the rate changes based on one side or both sides.', max_length=30, verbose_name='side mode'),
        ),
        migrations.AlterField(
            model_name='printingrate',
            name='double_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional duplex-per-sheet override. Leave blank to calculate from per-side price plus any duplex surcharge.', max_digits=12, null=True, verbose_name='double price'),
        ),
        migrations.AlterField(
            model_name='printingrate',
            name='single_price',
            field=models.DecimalField(decimal_places=2, help_text='Base print charge per side. Simplex uses this once; duplex uses it twice.', max_digits=12, verbose_name='single price'),
        ),
    ]
