# Generated by Django 5.2.11 on 2026-04-02 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_printingrate_duplex_surcharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingrate',
            name='duplex_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Optional flat surcharge added once per duplex sheet when the surcharge rule applies.', max_digits=12, verbose_name='duplex surcharge'),
        ),
        migrations.AlterField(
            model_name='printingrate',
            name='single_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Base print charge per side. Simplex uses this once; duplex uses it twice.', max_digits=12, verbose_name='single price'),
        ),
    ]
