# Generated by Django 5.2.11 on 2026-03-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0004_add_shop_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique per shop or global.', max_length=100, verbose_name='slug')),
                ('icon_svg_path', models.TextField(blank=True, default='', verbose_name='icon SVG path')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('shop', models.ForeignKey(blank=True, help_text='Null = global category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_categories', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='products/previews/', verbose_name='preview image')),
                ('dimensions_label', models.CharField(blank=True, default='', help_text='e.g. 90 × 55 mm', max_length=100, verbose_name='dimensions label')),
                ('weight_label', models.CharField(blank=True, default='', help_text='e.g. 350gsm', max_length=100, verbose_name='weight label')),
                ('is_popular', models.BooleanField(default=False, verbose_name='is popular')),
                ('is_best_value', models.BooleanField(default=False, verbose_name='is best value')),
                ('is_new', models.BooleanField(default=False, verbose_name='is new')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('shop', models.ForeignKey(blank=True, help_text='Null = global product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_products', to='shops.shop', verbose_name='shop')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gallery.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'gallery product',
                'verbose_name_plural': 'gallery products',
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='gallery_category_shop_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='gallery_category_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='gallery_product_shop_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='gallery_product_global_slug_unique'),
        ),
    ]
