# Generated by Django 5.2.11 on 2026-03-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page view'), ('search', 'Search'), ('product_view', 'Product view'), ('shop_view', 'Shop view'), ('quote_start', 'Quote start'), ('quote_submit', 'Quote submit'), ('login', 'Login'), ('signup', 'Signup'), ('api_error', 'API error'), ('frontend_error', 'Frontend error')], help_text='Normalized analytics event type.', max_length=32, verbose_name='event type')),
                ('session_key', models.CharField(blank=True, default='', help_text='Opaque session identifier when available.', max_length=64, verbose_name='session key')),
                ('visitor_id', models.CharField(blank=True, default='', help_text='Anonymous visitor identifier from client headers or cookies.', max_length=128, verbose_name='visitor id')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address as observed by the backend.', null=True, unpack_ipv4=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Client user agent string.', max_length=512, verbose_name='user agent')),
                ('referer', models.CharField(blank=True, default='', help_text='HTTP referer or frontend route context.', max_length=1024, verbose_name='referer')),
                ('path', models.CharField(blank=True, default='', help_text='Request path or frontend route.', max_length=1024, verbose_name='path')),
                ('method', models.CharField(blank=True, default='', help_text='HTTP method when event came from a request.', max_length=16, verbose_name='method')),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='Normalized request query parameters.', verbose_name='query params')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Non-PII event metadata for analytics slices.', verbose_name='metadata')),
                ('country', models.CharField(blank=True, default='', help_text='Resolved country for coarse analytics.', max_length=100, verbose_name='country')),
                ('city', models.CharField(blank=True, default='', help_text='Resolved city for coarse analytics.', max_length=100, verbose_name='city')),
                ('region', models.CharField(blank=True, default='', help_text='Resolved region or state for coarse analytics.', max_length=100, verbose_name='region')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code when the event maps to a response.', null=True, verbose_name='status code')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was recorded.', verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user tied to this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'analytics event',
                'verbose_name_plural': 'analytics events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='analytics_type_created_idx'), models.Index(fields=['user', '-created_at'], name='analytics_user_created_idx'), models.Index(fields=['session_key', '-created_at'], name='analytics_session_created_idx'), models.Index(fields=['visitor_id', '-created_at'], name='analytics_visitor_created_idx'), models.Index(fields=['path', '-created_at'], name='analytics_path_created_idx'), models.Index(fields=['status_code', '-created_at'], name='analytics_status_created_idx'), models.Index(fields=['country', 'region', 'city'], name='analytics_geo_idx'), models.Index(fields=['-created_at'], name='analytics_created_idx')],
            },
        ),
    ]
