# Generated by Django 5.2.11 on 2026-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "path", "-created_at"],
                name="analytics_type_path_ct_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="analytics_ip_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "country", "city"],
                name="analytics_type_geo_idx",
            ),
        ),
    ]
