# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Required feedback text.', verbose_name='message')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1–5 rating.', null=True, verbose_name='rating')),
                ('page', models.CharField(blank=True, help_text='Route or page context.', max_length=255, null=True, verbose_name='page')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'beta feedback',
                'verbose_name_plural': 'beta feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
