# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='order number')),
                ('title', models.CharField(default='', help_text='Job title or description.', max_length=255, verbose_name='title')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total quantity ordered.', verbose_name='quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('delivery_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('n_a', 'N/A (pickup)')], default='', help_text='Delivery tracking: pending, ready_for_pickup, shipped, delivered, or n_a for pickup.', max_length=20, verbose_name='delivery status')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the order was delivered to the customer.', null=True, verbose_name='delivered at')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('quote', models.ForeignKey(blank=True, help_text='Accepted shop quote this order was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='quotes.quote', verbose_name='shop quote')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'production order',
                'verbose_name_plural': 'production orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
