# Generated by Django 5.2.11 on 2026-03-14 20:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_add_productcategory_timestamps'),
        ('pricing', '0004_initial'),
        ('shops', '0003_shop_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_clients', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='order number')),
                ('title', models.CharField(default='', help_text='Job title or description.', max_length=255, verbose_name='title')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total quantity ordered.', verbose_name='quantity')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='production.client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_operators', to='shops.shop', verbose_name='shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_operator_profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'operator',
                'verbose_name_plural': 'operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='e.g. per_sheet, per_piece, per_sqm, flat')),
                ('unit_label', models.CharField(blank=True, default='', max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_pricing_methods', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'pricing method',
                'verbose_name_plural': 'pricing methods',
                'ordering': ['name'],
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='e.g. printing, lamination, cutting, binding')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_processes', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
                'ordering': ['display_order', 'name'],
                'unique_together': {('shop', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('unit', models.CharField(default='SHEET', help_text='SHEET, SQM, ROLL, etc.', max_length=20)),
                ('pricing_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_materials', to='pricing.material', verbose_name='pricing material')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_materials', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'production material',
                'verbose_name_plural': 'production materials',
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('qty_input', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='qty input')),
                ('waste', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='waste')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='default rate')),
                ('applied_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='applied rate')),
                ('billable_units', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='billable units')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='line total')),
                ('notes', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='production.job', verbose_name='job')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.operator', verbose_name='operator')),
                ('pricing_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.pricingmethod', verbose_name='pricing method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_processes', to='production.process', verbose_name='process')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.productionmaterial', verbose_name='material')),
            ],
            options={
                'verbose_name': 'job process',
                'verbose_name_plural': 'job processes',
                'ordering': ['date', 'process__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='')),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_products', to='catalog.product', verbose_name='catalog product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_products', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'production product',
                'verbose_name_plural': 'production products',
                'ordering': ['name'],
                'unique_together': {('shop', 'name')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='production.productionproduct', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='WastageStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastage_stages', to='production.process', verbose_name='process')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_wastage_stages', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'wastage stage',
                'verbose_name_plural': 'wastage stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='default rate')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_price_cards', to='shops.shop', verbose_name='shop')),
                ('pricing_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='production.pricingmethod', verbose_name='pricing method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='production.process', verbose_name='process')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_cards', to='production.productionmaterial', verbose_name='material')),
            ],
            options={
                'verbose_name': 'price card',
                'verbose_name_plural': 'price cards',
                'ordering': ['process', 'pricing_method'],
                'unique_together': {('process', 'pricing_method', 'material')},
            },
        ),
    ]
