# Generated by Django 5.2.11 on 2026-04-05 21:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'production product',
                'verbose_name_plural': 'production products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WastageStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'wastage stage',
                'verbose_name_plural': 'wastage stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_operators', to='shops.shop', verbose_name='shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_operator_profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'operator',
                'verbose_name_plural': 'operators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='e.g. per_sheet, per_piece, per_sqm, flat')),
                ('unit_label', models.CharField(blank=True, default='', max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_pricing_methods', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'pricing method',
                'verbose_name_plural': 'pricing methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='e.g. printing, lamination, cutting, binding')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_processes', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'process',
                'verbose_name_plural': 'processes',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('unit', models.CharField(default='SHEET', help_text='SHEET, SQM, ROLL, etc.', max_length=20)),
                ('pricing_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_materials', to='pricing.material', verbose_name='pricing material')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_materials', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'production material',
                'verbose_name_plural': 'production materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='default rate')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_price_cards', to='shops.shop', verbose_name='shop')),
                ('pricing_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='production.pricingmethod', verbose_name='pricing method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='production.process', verbose_name='process')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_cards', to='production.productionmaterial', verbose_name='material')),
            ],
            options={
                'verbose_name': 'price card',
                'verbose_name_plural': 'price cards',
                'ordering': ['process', 'pricing_method'],
            },
        ),
        migrations.CreateModel(
            name='JobProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('qty_input', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='qty input')),
                ('waste', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='waste')),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='default rate')),
                ('applied_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='applied rate')),
                ('billable_units', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='billable units')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='line total')),
                ('notes', models.TextField(blank=True, default='')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.operator', verbose_name='operator')),
                ('pricing_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.pricingmethod', verbose_name='pricing method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_processes', to='production.process', verbose_name='process')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_processes', to='production.productionmaterial', verbose_name='material')),
            ],
            options={
                'verbose_name': 'job process',
                'verbose_name_plural': 'job processes',
                'ordering': ['date', 'process__display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='order number')),
                ('title', models.CharField(default='', help_text='Job title or description.', max_length=255, verbose_name='title')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Total quantity ordered.', verbose_name='quantity')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('delivery_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('n_a', 'N/A (pickup)')], default='', help_text='Delivery tracking: pending, ready_for_pickup, shipped, delivered, or n_a for pickup.', max_length=20, verbose_name='delivery status')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the order was delivered to the customer.', null=True, verbose_name='delivered at')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.customer', verbose_name='customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'production order',
                'verbose_name_plural': 'production orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
