# Generated by Django 5.2.11 on 2026-04-05 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('production', '0001_initial'),
        ('quotes', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='shop_quote',
            field=models.ForeignKey(blank=True, help_text='Accepted shop quote this order was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='quotes.shopquote', verbose_name='shop quote'),
        ),
        migrations.AddField(
            model_name='jobprocess',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='productionproduct',
            name='catalog_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_products', to='catalog.product', verbose_name='catalog product'),
        ),
        migrations.AddField(
            model_name='productionproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_products', to='shops.shop', verbose_name='shop'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionproduct', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='wastagestage',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastage_stages', to='production.process', verbose_name='process'),
        ),
        migrations.AddField(
            model_name='wastagestage',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_wastage_stages', to='shops.shop', verbose_name='shop'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pricingmethod',
            unique_together={('shop', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('shop', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productionmaterial',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pricecard',
            unique_together={('shop', 'process', 'pricing_method')},
        ),
        migrations.AlterUniqueTogether(
            name='productionproduct',
            unique_together={('shop', 'name')},
        ),
    ]
