# Generated by Django 5.2.11 on 2026-03-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_shop_quote_and_status'),
        ('quotes', '0008_remove_quote_request_legacy_fields'),
        ('shops', '0005_add_google_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'production order', 'verbose_name_plural': 'production orders'},
        ),
        migrations.AddField(
            model_name='productionorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the order was delivered to the customer.', null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('n_a', 'N/A (pickup)')], default='', help_text='Delivery tracking: pending, ready_for_pickup, shipped, delivered, or n_a for pickup.', max_length=20, verbose_name='delivery status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='shops.shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='jobprocess',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.productionproduct', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='shops.shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='shop_quote',
            field=models.ForeignKey(blank=True, help_text='Accepted shop quote this order was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='quotes.shopquote', verbose_name='shop quote'),
        ),
        migrations.AlterUniqueTogether(
            name='pricecard',
            unique_together={('shop', 'process', 'pricing_method')},
        ),
    ]
