# Generated by Django 5.2.11 on 2026-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_userprofile_usersociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('shop_owner', 'Shop Owner'), ('staff', 'Staff'), ('CUSTOMER', 'Customer (Legacy)'), ('PRINTER', 'Printer (Legacy)')], default='client', help_text='Primary account role used by the dashboard UI.', max_length=20),
        ),
    ]
