# Generated by Django 5.2.11 on 2026-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_capability_foundations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('broker', 'Broker'), ('shop_owner', 'Shop Owner'), ('staff', 'Staff')], default='client', help_text='Primary account role used by the dashboard UI.', max_length=20),
        ),
    ]
