# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name (e.g. SRA3, A4, Business Card).', max_length=100, verbose_name='name')),
                ('width_mm', models.PositiveIntegerField(help_text='Width in millimeters.', verbose_name='width (mm)')),
                ('height_mm', models.PositiveIntegerField(help_text='Height in millimeters.', verbose_name='height (mm)')),
                ('size_type', models.CharField(choices=[('PRODUCTION', 'Production (parent/press sheet)'), ('FINAL', 'Final (finished size)')], default='FINAL', editable=False, max_length=20, verbose_name='size type')),
            ],
            options={
                'verbose_name': 'final paper size',
                'verbose_name_plural': 'final paper sizes',
                'ordering': ['width_mm', 'height_mm'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(help_text='Display name (e.g. SRA3, A4, Business Card).', max_length=100, verbose_name='name')),
                ('width_mm', models.PositiveIntegerField(help_text='Width in millimeters.', verbose_name='width (mm)')),
                ('height_mm', models.PositiveIntegerField(help_text='Height in millimeters.', verbose_name='height (mm)')),
                ('size_type', models.CharField(choices=[('PRODUCTION', 'Production (parent/press sheet)'), ('FINAL', 'Final (finished size)')], default='PRODUCTION', editable=False, max_length=20, verbose_name='size type')),
                ('code', models.CharField(help_text='Short code for matching (e.g. SRA3, A3, B2). Used by PrintingRate.', max_length=30, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': 'production paper size',
                'verbose_name_plural': 'production paper sizes',
                'ordering': ['width_mm', 'height_mm'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(default='', help_text='Display name of the machine.', max_length=255, verbose_name='name')),
                ('machine_type', models.CharField(choices=[('OFFSET', 'Offset'), ('DIGITAL', 'Digital'), ('LARGE_FORMAT', 'Large Format')], default='DIGITAL', help_text='Type of printing machine (offset, digital, large format).', max_length=20, verbose_name='machine type')),
                ('max_width_mm', models.PositiveIntegerField(help_text='Maximum printable width in millimeters.', verbose_name='max width (mm)')),
                ('max_height_mm', models.PositiveIntegerField(help_text='Maximum printable height in millimeters.', verbose_name='max height (mm)')),
                ('min_gsm', models.PositiveIntegerField(blank=True, help_text='Minimum paper weight (grams per square metre) supported.', null=True, verbose_name='min GSM')),
                ('max_gsm', models.PositiveIntegerField(blank=True, help_text='Maximum paper weight (grams per square metre) supported.', null=True, verbose_name='max GSM')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the machine is active and available.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this machine.', on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'machine',
                'verbose_name_plural': 'machines',
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('CUSTOM', 'Custom')], default='A4', help_text='Standard sheet size (A4, A3, SRA3, etc.). Kept for PrintingRate matching.', max_length=20, verbose_name='sheet size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight in grams per square metre.', verbose_name='GSM')),
                ('paper_type', models.CharField(choices=[('COATED', 'Coated'), ('UNCOATED', 'Uncoated'), ('RECYCLED', 'Recycled'), ('GLOSS', 'Gloss'), ('MATTE', 'Matte'), ('OTHER', 'Other')], default='UNCOATED', help_text='Type of paper (coated, uncoated, gloss, etc.).', max_length=20, verbose_name='paper type')),
                ('width_mm', models.PositiveIntegerField(blank=True, help_text='Sheet width in millimeters (auto-filled from sheet size).', null=True, verbose_name='width (mm)')),
                ('height_mm', models.PositiveIntegerField(blank=True, help_text='Sheet height in millimeters (auto-filled from sheet size).', null=True, verbose_name='height (mm)')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price per sheet.', max_digits=12, verbose_name='buying price')),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price per sheet.', max_digits=12, verbose_name='selling price')),
                ('quantity_in_stock', models.PositiveIntegerField(blank=True, help_text='Number of sheets currently in stock.', null=True, verbose_name='quantity in stock')),
                ('reorder_level', models.PositiveIntegerField(blank=True, help_text='Stock level that triggers reorder alert.', null=True, verbose_name='reorder level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this paper stock is active.', verbose_name='is active')),
                ('shop', models.ForeignKey(help_text='Shop that owns this paper stock.', on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='shops.shop', verbose_name='shop')),
                ('production_size', models.ForeignKey(blank=True, help_text='Parent sheet size for imposition. When set, width/height come from here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='inventory.productionpapersize', verbose_name='production size')),
            ],
            options={
                'verbose_name': 'paper',
                'verbose_name_plural': 'papers',
                'ordering': ['shop', 'sheet_size', 'gsm', 'paper_type'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'sheet_size', 'gsm', 'paper_type'), name='unique_shop_sheet_gsm_paper')],
            },
        ),
    ]
