# Generated by Django 5.2.11 on 2026-04-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='category',
            field=models.CharField(choices=[('matt', 'Matt'), ('gloss', 'Gloss'), ('bond', 'Bond'), ('ivory', 'Ivory'), ('tictac', 'Tictac'), ('conqueror', 'Conqueror'), ('artcard', 'Art Card'), ('cover_board', 'Cover Board'), ('kraft', 'Kraft'), ('special', 'Special Paper'), ('other', 'Other')], default='other', help_text='Marketplace-facing category such as matt, tictac, conqueror, bond, or cover board.', max_length=30, verbose_name='paper category'),
        ),
        migrations.AddField(
            model_name='paper',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Human-ready stock label shown in calculator dropdowns (e.g. Matt 130gsm, Conqueror 120gsm).', max_length=255, verbose_name='display name'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_cover_stock',
            field=models.BooleanField(default=False, help_text='Whether this stock is suitable for booklet covers or heavier cover applications.', verbose_name='is cover stock'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_insert_stock',
            field=models.BooleanField(default=False, help_text='Whether this stock is suitable for booklet inserts or inner pages.', verbose_name='is insert stock'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_specialty',
            field=models.BooleanField(default=False, help_text='Marks specialty papers such as conqueror, ivory, kraft, or custom branded stocks.', verbose_name='is specialty'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_sticker_stock',
            field=models.BooleanField(default=False, help_text='Whether this stock is suitable for label stickers / tictac work.', verbose_name='is sticker stock'),
        ),
    ]
