# Generated by Django 5.2.11 on 2026-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this paper for imposition/pricing when no paper is specified. Selection order: default paper > most economical (lowest cost per sheet) > only available.', verbose_name='is default'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('shop',), name='unique_shop_default_paper'),
        ),
    ]
