# Generated by Django 5.2.11 on 2026-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_paper_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional name for the paper (e.g. Art 130).', max_length=255, verbose_name='name'),
        ),
    ]
