# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Display name of the print shop.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the shop.', max_length=100, null=True, unique=True, verbose_name='slug')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code (e.g. USD, EUR).', max_length=3, verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shop is active and visible.', verbose_name='is active')),
                ('description', models.TextField(blank=True, default='', help_text='Business description for the shop.', verbose_name='description')),
                ('business_email', models.EmailField(blank=True, default='', help_text='Contact email for the shop.', max_length=254, verbose_name='business email')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone for the shop.', max_length=32, verbose_name='phone number')),
                ('address_line', models.CharField(blank=True, default='', help_text='Street address.', max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, default='', help_text='City.', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='', help_text='State or province.', max_length=100, verbose_name='state or province')),
                ('country', models.CharField(blank=True, default='', help_text='Country.', max_length=100, verbose_name='country')),
                ('zip_code', models.CharField(blank=True, default='', help_text='Postal or ZIP code.', max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geo search.', max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geo search.', max_digits=9, null=True, verbose_name='longitude')),
                ('pricing_ready', models.BooleanField(default=False, help_text='Denormalized flag: True when shop has at least one machine, paper, and printing rate.', verbose_name='pricing ready')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('owner', models.ForeignKey(help_text='User who owns this shop.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'favorite shop',
                'verbose_name_plural': 'favorite shops',
            },
        ),
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating 1-5.', verbose_name='stars')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shops.shop', verbose_name='shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'shop rating',
                'verbose_name_plural': 'shop ratings',
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoriteshop',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoprating',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_rating'),
        ),
    ]
