# Generated by Django 5.2.11 on 2026-04-12 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Display name of the print shop.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the shop.', max_length=100, null=True, unique=True, verbose_name='slug')),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 currency code (e.g. KES, USD).', max_length=3, verbose_name='currency')),
                ('is_vat_enabled', models.BooleanField(default=False, help_text='Whether VAT should be applied to quote calculations for this shop.', verbose_name='VAT enabled')),
                ('vat_rate', models.DecimalField(decimal_places=2, default='16.00', help_text='VAT rate percentage applied when VAT is enabled.', max_digits=5, verbose_name='VAT rate')),
                ('vat_mode', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], default='exclusive', help_text='Whether prices returned by the pricing engine are VAT-inclusive or VAT-exclusive.', max_length=20, verbose_name='VAT mode')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shop is active and visible.', verbose_name='is active')),
                ('description', models.TextField(blank=True, default='Business description for the shop.', help_text='Business description for the shop.', verbose_name='description')),
                ('business_email', models.EmailField(blank=True, default='shop@printy.ke', help_text='Contact email for the shop.', max_length=254, verbose_name='business email')),
                ('phone_number', models.CharField(blank=True, default='+254 700 000 000', help_text='Contact phone for the shop.', max_length=32, verbose_name='phone number')),
                ('address_line', models.CharField(blank=True, default='Street address', help_text='Street address.', max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, default='Nairobi', help_text='City.', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='Nairobi', help_text='State or province.', max_length=100, verbose_name='state or province')),
                ('country', models.CharField(blank=True, default='Kenya', help_text='Country.', max_length=100, verbose_name='country')),
                ('zip_code', models.CharField(blank=True, default='00100', help_text='Postal or ZIP code.', max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geo search.', max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geo search.', max_digits=9, null=True, verbose_name='longitude')),
                ('google_place_id', models.CharField(blank=True, default='', help_text='Stable identifier from Google Places for reuse and geocoding.', max_length=255, verbose_name='Google Place ID')),
                ('pricing_ready', models.BooleanField(default=False, help_text='Denormalized flag: True when shop has at least one machine, paper, and printing rate.', verbose_name='pricing ready')),
                ('public_match_ready', models.BooleanField(default=False, help_text='True when the shop can produce usable public calculator preview results.', verbose_name='public match ready')),
                ('supports_custom_requests', models.BooleanField(default=True, help_text='Whether public calculator custom requests can be matched to this shop.', verbose_name='supports custom requests')),
                ('supports_catalog_requests', models.BooleanField(default=True, help_text='Whether public catalog/tweak calculators can match against this shop.', verbose_name='supports catalog requests')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this shop can appear in public marketplace matching and browsing.', verbose_name='is public')),
                ('opening_time', models.TimeField(default='08:00', help_text='Default opening time (e.g. 08:00). Used when no per-day override in OpeningHours.', verbose_name='opening time')),
                ('closing_time', models.TimeField(default='18:00', help_text='Default closing time (e.g. 18:00). Used when no per-day override in OpeningHours.', verbose_name='closing time')),
                ('closing_soon_minutes', models.PositiveSmallIntegerField(default=30, help_text="Minutes before closing to show 'Closing soon' status (e.g. 30).", verbose_name='closing soon minutes')),
                ('timezone', models.CharField(default='Africa/Nairobi', help_text='IANA timezone used for ready-time projections (e.g. Africa/Nairobi).', max_length=64, verbose_name='timezone')),
                ('same_day_cutoff_time', models.TimeField(blank=True, help_text='Optional cutoff after which new work starts on the next working slot.', null=True, verbose_name='same-day cutoff time')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('location', models.ForeignKey(blank=True, help_text='SEO location (neighborhood/city) for marketplace pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='locations.location', verbose_name='location')),
                ('owner', models.ForeignKey(help_text='User who owns this shop.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_shops', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(default=1, help_text='1=Monday, 2=Tuesday, ..., 7=Sunday (ISO).', verbose_name='weekday')),
                ('from_hour', models.CharField(blank=True, default='08:00', help_text='Opening time (HH:MM format, e.g. 08:00).', max_length=5, verbose_name='from hour')),
                ('to_hour', models.CharField(blank=True, default='18:00', help_text='Closing time (HH:MM format, e.g. 18:00).', max_length=5, verbose_name='to hour')),
                ('is_closed', models.BooleanField(default=False, help_text='If True, shop is closed on this day.', verbose_name='closed')),
                ('shop', models.ForeignKey(help_text='Shop these hours belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'opening hours',
                'verbose_name_plural': 'opening hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_shops', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'favorite shop',
                'verbose_name_plural': 'favorite shops',
            },
        ),
        migrations.CreateModel(
            name='ShopMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=20)),
                ('can_manage_setup', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_pricing', models.BooleanField(default=False)),
                ('can_manage_quotes', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop membership',
                'verbose_name_plural': 'shop memberships',
            },
        ),
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating 1-5.', verbose_name='stars')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shops.shop', verbose_name='shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'shop rating',
                'verbose_name_plural': 'shop ratings',
            },
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_geo_idx'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.UniqueConstraint(fields=('shop', 'weekday'), name='unique_shop_weekday'),
        ),
        migrations.AddConstraint(
            model_name='favoriteshop',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shopmembership',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='unique_shop_membership'),
        ),
        migrations.AddConstraint(
            model_name='shoprating',
            constraint=models.UniqueConstraint(fields=('user', 'shop'), name='unique_user_shop_rating'),
        ),
    ]
