# Generated by Django 5.2.11 on 2026-03-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address_line',
            field=models.CharField(blank=True, default='', help_text='Street address.', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_email',
            field=models.EmailField(blank=True, default='', help_text='Contact email for the shop.', max_length=254, verbose_name='business email'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City.', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country.', max_length=100, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Business description for the shop.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Contact phone for the shop.', max_length=32, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State or province.', max_length=100, verbose_name='state or province'),
        ),
        migrations.AddField(
            model_name='shop',
            name='zip_code',
            field=models.CharField(blank=True, default='', help_text='Postal or ZIP code.', max_length=20, verbose_name='postal code'),
        ),
    ]
