# Generated by Django 5.2.11 on 2026-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='currency',
            field=models.CharField(default='KES', help_text='ISO 4217 currency code (e.g. KES, USD).', max_length=3, verbose_name='currency'),
        ),
    ]
