# Generated by Django 5.2.11 on 2026-05-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='opening_hours_text',
            field=models.CharField(blank=True, default='', help_text='Optional public summary such as Mon-Sat, 8am-6pm.', max_length=255, verbose_name='opening hours text'),
        ),
        migrations.AddField(
            model_name='shop',
            name='public_email',
            field=models.EmailField(blank=True, default='', help_text='Optional public contact email intentionally shared with buyers.', max_length=254, verbose_name='public email'),
        ),
        migrations.AddField(
            model_name='shop',
            name='public_whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Optional WhatsApp/business number intentionally shared with buyers.', max_length=32, verbose_name='public WhatsApp number'),
        ),
        migrations.AddField(
            model_name='shop',
            name='service_area',
            field=models.CharField(blank=True, default='', help_text='Public-facing areas or delivery coverage for this shop.', max_length=255, verbose_name='service area'),
        ),
        migrations.AddField(
            model_name='shop',
            name='turnaround_statement',
            field=models.CharField(blank=True, default='', help_text='Short public-facing turnaround summary shown to buyers.', max_length=255, verbose_name='turnaround statement'),
        ),
    ]
