# Generated by Django 5.2.11 on 2026-03-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('shops', '0002_default_currency_kes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location',
            field=models.ForeignKey(blank=True, help_text='SEO location (neighborhood/city) for marketplace pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='locations.location', verbose_name='location'),
        ),
    ]
