# Generated by Django 5.2.11 on 2026-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_add_shop_contact_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pricing_ready',
            field=models.BooleanField(default=False, help_text='Denormalized flag: True when shop has at least one machine, paper, and printing rate.', verbose_name='pricing ready'),
        ),
    ]
