# Generated by Django 5.2.11 on 2026-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_opening_hours_text_shop_public_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pricing_ranges',
            field=models.JSONField(blank=True, default=None, help_text='Market-intelligence pricing ranges per product type. Keys: booklets, flyers, posters, business_cards. Each value: {low: KES, high: KES}.', null=True, verbose_name='pricing ranges'),
        ),
    ]
