# Generated by Django 5.2.11 on 2026-03-15 13:26

import django.db.models.deletion
from django.db import migrations, models


def create_default_opening_hours(apps, schema_editor):
    """Create Mon–Fri 08:00–18:00, Sat–Sun closed for each existing shop."""
    Shop = apps.get_model("shops", "Shop")
    OpeningHours = apps.get_model("shops", "OpeningHours")
    defaults = [
        (1, "08:00", "18:00", False),  # Mon
        (2, "08:00", "18:00", False),  # Tue
        (3, "08:00", "18:00", False),  # Wed
        (4, "08:00", "18:00", False),  # Thu
        (5, "08:00", "18:00", False),  # Fri
        (6, "", "", True),   # Sat closed
        (7, "", "", True),  # Sun closed
    ]
    for shop in Shop.objects.all():
        for weekday, from_hour, to_hour, is_closed in defaults:
            OpeningHours.objects.get_or_create(
                shop=shop, weekday=weekday,
                defaults={"from_hour": from_hour, "to_hour": to_hour, "is_closed": is_closed},
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_soon_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text="Minutes before closing to show 'Closing soon' status (e.g. 30).", verbose_name='closing soon minutes'),
        ),
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='Default closing time (e.g. 18:00). Used when no per-day override in OpeningHours.', verbose_name='closing time'),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_time',
            field=models.TimeField(default='08:00', help_text='Default opening time (e.g. 08:00). Used when no per-day override in OpeningHours.', verbose_name='opening time'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_line',
            field=models.CharField(blank=True, default='Street address', help_text='Street address.', max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_email',
            field=models.EmailField(blank=True, default='shop@example.com', help_text='Contact email for the shop.', max_length=254, verbose_name='business email'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, default='Nairobi', help_text='City.', max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='country',
            field=models.CharField(blank=True, default='Kenya', help_text='Country.', max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True, default='Business description for the shop.', help_text='Business description for the shop.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, default='+254 700 000 000', help_text='Contact phone for the shop.', max_length=32, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.CharField(blank=True, default='Nairobi', help_text='State or province.', max_length=100, verbose_name='state or province'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='zip_code',
            field=models.CharField(blank=True, default='00100', help_text='Postal or ZIP code.', max_length=20, verbose_name='postal code'),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(default=1, help_text='1=Monday, 2=Tuesday, ..., 7=Sunday (ISO).', verbose_name='weekday')),
                ('from_hour', models.CharField(blank=True, default='08:00', help_text='Opening time (HH:MM format, e.g. 08:00).', max_length=5, verbose_name='from hour')),
                ('to_hour', models.CharField(blank=True, default='18:00', help_text='Closing time (HH:MM format, e.g. 18:00).', max_length=5, verbose_name='to hour')),
                ('is_closed', models.BooleanField(default=False, help_text='If True, shop is closed on this day.', verbose_name='closed')),
                ('shop', models.ForeignKey(help_text='Shop these hours belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'opening hours',
                'verbose_name_plural': 'opening hours',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('shop', 'weekday'), name='unique_shop_weekday')],
            },
        ),
        migrations.RunPython(create_default_opening_hours, noop),
    ]
