# Generated by Django 5.2.11 on 2026-03-05 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_add_product_status_and_pricing_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geo search.', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geo search.', max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['latitude', 'longitude'], name='shops_geo_idx'),
        ),
    ]
