# Generated by Django 5.2.11 on 2026-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_add_opening_hours_and_shop_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='google_place_id',
            field=models.CharField(blank=True, default='', help_text='Stable identifier from Google Places for reuse and geocoding.', max_length=255, verbose_name='Google Place ID'),
        ),
    ]
