# Generated by Django 5.2.11 on 2026-03-26 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_add_google_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=20)),
                ('can_manage_setup', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_pricing', models.BooleanField(default=False)),
                ('can_manage_quotes', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shop membership',
                'verbose_name_plural': 'shop memberships',
                'constraints': [models.UniqueConstraint(fields=('shop', 'user'), name='unique_shop_membership')],
            },
        ),
    ]
