# Generated by Django 5.2.11 on 2026-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shop_vat_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this shop can appear in public marketplace matching and browsing.', verbose_name='is public'),
        ),
        migrations.AddField(
            model_name='shop',
            name='public_match_ready',
            field=models.BooleanField(default=False, help_text='True when the shop can produce usable public calculator preview results.', verbose_name='public match ready'),
        ),
        migrations.AddField(
            model_name='shop',
            name='supports_catalog_requests',
            field=models.BooleanField(default=True, help_text='Whether public catalog/tweak calculators can match against this shop.', verbose_name='supports catalog requests'),
        ),
        migrations.AddField(
            model_name='shop',
            name='supports_custom_requests',
            field=models.BooleanField(default=True, help_text='Whether public calculator custom requests can be matched to this shop.', verbose_name='supports custom requests'),
        ),
    ]
