# Generated by Django 5.2.11 on 2026-04-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_shop_is_public_shop_public_match_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='same_day_cutoff_time',
            field=models.TimeField(blank=True, help_text='Optional cutoff after which new work starts on the next working slot.', null=True, verbose_name='same-day cutoff time'),
        ),
        migrations.AddField(
            model_name='shop',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', help_text='IANA timezone used for ready-time projections (e.g. Africa/Nairobi).', max_length=64, verbose_name='timezone'),
        ),
    ]
