# Generated by Django 5.2.11 on 2026-09-13 20:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa access token',
                'verbose_name_plural': 'M-Pesa access tokens',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, default='', max_length=64)),
                ('result_code', models.CharField(blank=True, default='', max_length=12)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('duplicate', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'M-Pesa callback log',
                'verbose_name_plural': 'M-Pesa callback logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Normalized MSISDN in 2547XXXXXXXX form.', max_length=20, verbose_name='phone number')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expected amount in KES.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='amount')),
                ('currency', models.CharField(default='KES', editable=False, max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('needs_review', 'Needs review')], db_index=True, default='initiated', max_length=20, verbose_name='status')),
                ('reconciliation_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('amount_mismatch', 'Amount mismatch'), ('duplicate', 'Duplicate'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=24, verbose_name='reconciliation status')),
                ('account_reference', models.CharField(default='PRINTY', help_text="Shown on the customer's M-Pesa statement.", max_length=40, verbose_name='account reference')),
                ('description', models.CharField(default='Printy payment', max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('customer_message', models.TextField(blank=True, default='')),
                ('mpesa_receipt_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount reported by the callback. Compare against `amount`.', max_digits=12, null=True)),
                ('result_code', models.CharField(blank=True, default='', max_length=12)),
                ('result_desc', models.TextField(blank=True, default='')),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('stk_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Account that initiated the payment. Null if guest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'M-Pesa payment',
                'verbose_name_plural': 'M-Pesa payments',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['status', 'reconciliation_status'], name='mpesa_payme_status_edf62d_idx'), models.Index(fields=['-initiated_at'], name='mpesa_payme_initiat_75eb2c_idx'), models.Index(fields=['content_type', 'object_id'], name='mpesa_payme_content_e77d6c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('1.00'))), name='mpesa_amount_minimum_one_shilling')],
            },
        ),
    ]
