# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per billing period.', max_digits=12, verbose_name='price')),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='billing period')),
            ],
            options={
                'verbose_name': 'subscription plan',
                'verbose_name_plural': 'subscription plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20, verbose_name='status')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='period end')),
                ('next_billing_date', models.DateField(blank=True, null=True, verbose_name='next billing date')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='last payment date')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shops.shop', verbose_name='shop')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('method', models.CharField(choices=[('MPESA_C2B', 'M-Pesa C2B')], default='MPESA_C2B', max_length=20, verbose_name='method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('receipt_number', models.CharField(blank=True, default='', max_length=50, verbose_name='receipt number')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', help_text='CheckoutRequestID or similar.', max_length=100, verbose_name='request id')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='period end')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription', verbose_name='subscription')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='MpesaStkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('checkout_request_id', models.CharField(db_index=True, help_text='From Daraja STK push response.', max_length=100, unique=True, verbose_name='checkout request id')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20, verbose_name='status')),
                ('raw_callback_payload', models.JSONField(blank=True, null=True, verbose_name='raw callback payload')),
                ('receipt_number', models.CharField(blank=True, default='', max_length=50, verbose_name='receipt number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_stk_requests', to='shops.shop', verbose_name='shop')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_stk_requests', to='subscriptions.subscriptionplan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'M-Pesa STK request',
                'verbose_name_plural': 'M-Pesa STK requests',
            },
        ),
    ]
