# Generated by Django 5.2.11 on 2026-03-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price'], 'verbose_name': 'subscription plan', 'verbose_name_plural': 'subscription plans'},
        ),
    ]
