# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique per shop or global.', max_length=100, verbose_name='slug')),
                ('icon_svg_path', models.TextField(blank=True, default='', verbose_name='icon SVG path')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('shop', models.ForeignKey(blank=True, help_text='Null = global category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(default='', help_text='Display name of the product.', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', help_text='Product description.', verbose_name='description')),
                ('slug', models.SlugField(blank=True, default='', help_text='URL-friendly identifier. Unique per shop.', max_length=100, verbose_name='slug')),
                ('pricing_mode', models.CharField(choices=[('SHEET', 'Sheet'), ('LARGE_FORMAT', 'Large Format')], default='SHEET', help_text='Sheet or large format pricing.', max_length=20, verbose_name='pricing mode')),
                ('default_finished_width_mm', models.PositiveIntegerField(default=0, help_text='Default finished width in millimeters. Required for price range.', verbose_name='default finished width (mm)')),
                ('default_finished_height_mm', models.PositiveIntegerField(default=0, help_text='Default finished height in millimeters. Required for price range.', verbose_name='default finished height (mm)')),
                ('default_bleed_mm', models.PositiveIntegerField(default=3, help_text='Bleed for imposition (default 3mm). Used to calculate copies per sheet.', verbose_name='bleed (mm)')),
                ('default_sides', models.CharField(choices=[('SIMPLEX', 'Simplex (1-sided)'), ('DUPLEX', 'Duplex (2-sided)')], default='SIMPLEX', help_text='Default simplex or duplex.', max_length=10, verbose_name='default sides')),
                ('min_quantity', models.PositiveIntegerField(default=100, help_text='Minimum order quantity for price range calculation.', verbose_name='min quantity')),
                ('default_sheet_size', models.CharField(blank=True, default='', help_text='Preferred sheet size for price range est. (e.g. SRA3). Blank = infer from shop.', max_length=20, verbose_name='default sheet size')),
                ('min_width_mm', models.PositiveIntegerField(blank=True, help_text='Min width for LARGE_FORMAT price range (defaults to default_finished_width_mm).', null=True, verbose_name='min width (mm)')),
                ('min_height_mm', models.PositiveIntegerField(blank=True, help_text='Min height for LARGE_FORMAT price range (defaults to default_finished_height_mm).', null=True, verbose_name='min height (mm)')),
                ('max_width_mm', models.PositiveIntegerField(blank=True, help_text='Max finished width (e.g. 105 for A6 business cards). Rejects larger sizes.', null=True, verbose_name='max width (mm)')),
                ('max_height_mm', models.PositiveIntegerField(blank=True, help_text='Max finished height (e.g. 148 for A6). Rejects larger sizes.', null=True, verbose_name='max height (mm)')),
                ('allowed_sheet_sizes', models.JSONField(blank=True, help_text='List of allowed parent sheet codes (e.g. ["A4","A3","SRA3"]). Empty = no restriction.', null=True, verbose_name='allowed sheet sizes')),
                ('min_gsm', models.PositiveIntegerField(blank=True, help_text='Minimum paper grammage allowed (e.g. 250 for business cards).', null=True, verbose_name='min GSM')),
                ('max_gsm', models.PositiveIntegerField(blank=True, help_text='Maximum paper grammage allowed (e.g. 350 for business cards, 170 for flyers).', null=True, verbose_name='max GSM')),
                ('min_area_m2', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.50'), help_text='Minimum printable area in m² for LARGE_FORMAT products. Default 0.5 m².', max_digits=8, null=True, verbose_name='min area (m²)')),
                ('allow_simplex', models.BooleanField(default=True, help_text='Allow single-sided printing.', verbose_name='allow simplex')),
                ('allow_duplex', models.BooleanField(default=True, help_text='Allow double-sided printing.', verbose_name='allow duplex')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNAVAILABLE', 'Unavailable')], default='DRAFT', help_text='DRAFT = not visible to buyers. PUBLISHED = visible if shop pricing ready. UNAVAILABLE = hidden.', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is active.', verbose_name='is active')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated lowest price for this product (display only).', max_digits=12, null=True, verbose_name='lowest price (est.)')),
                ('highest_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated highest price for this product (display only).', max_digits=12, null=True, verbose_name='highest price (est.)')),
                ('dimensions_label', models.CharField(blank=True, default='', help_text='e.g. 90 × 55 mm', max_length=100, verbose_name='dimensions label')),
                ('weight_label', models.CharField(blank=True, default='', help_text='e.g. 350gsm', max_length=100, verbose_name='weight label')),
                ('is_popular', models.BooleanField(default=False, verbose_name='is popular')),
                ('is_best_value', models.BooleanField(default=False, verbose_name='is best value')),
                ('is_new', models.BooleanField(default=False, verbose_name='is new')),
                ('shop', models.ForeignKey(help_text='Shop that owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name='shop')),
                ('category', models.ForeignKey(blank=True, help_text='Product category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFinishingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default finishing option.', verbose_name='is default')),
                ('price_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text='Optional price adjustment for this finishing.', max_digits=12, null=True, verbose_name='price adjustment')),
                ('apply_to_sides', models.CharField(choices=[('SINGLE', 'Single-sided'), ('DOUBLE', 'Double-sided'), ('BOTH', 'Both (follows print sides)')], default='BOTH', help_text='Single-sided, double-sided, or both (follows print sides).', max_length=10, verbose_name='apply to sides')),
                ('finishing_rate', models.ForeignKey(help_text='Finishing rate for this option.', on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='pricing.finishingrate', verbose_name='finishing rate')),
                ('product', models.ForeignKey(help_text='Product this option applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='finishing_options', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product finishing option',
                'verbose_name_plural': 'product finishing options',
                'ordering': ['product', 'finishing_rate'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('image', models.ImageField(help_text='Product image.', upload_to='products/', verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='Use as main/preview image for cards and listings.', verbose_name='is primary')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first).', verbose_name='display order')),
                ('product', models.ForeignKey(help_text='Product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['product', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Imposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3'), ('A2', 'A2'), ('A1', 'A1'), ('A0', 'A0'), ('CUSTOM', 'Custom')], default='A4', help_text='Paper sheet size (A4, A3, etc.).', max_length=20, verbose_name='sheet size')),
                ('copies_per_sheet', models.PositiveIntegerField(default=1, help_text='Number of product copies that fit on one sheet (e.g. 8 for business cards on A4).', verbose_name='copies per sheet')),
                ('is_default', models.BooleanField(default=False, help_text='Use this imposition by default for this product.', verbose_name='is default')),
                ('product', models.ForeignKey(help_text='Product this imposition applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='impositions', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'imposition',
                'verbose_name_plural': 'impositions',
                'ordering': ['product', 'sheet_size'],
                'constraints': [models.UniqueConstraint(fields=('product', 'sheet_size'), name='unique_product_sheet_imposition')],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='catalog_category_shop_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='catalog_category_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='catalog_product_shop_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='productfinishingoption',
            constraint=models.UniqueConstraint(fields=('product', 'finishing_rate'), name='unique_product_finishing'),
        ),
    ]
