# Generated by Django 5.2.11 on 2026-09-11 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfinishingoption',
            name='finishing_rate',
            field=models.ForeignKey(help_text='Finishing rate for this option.', on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='pricing.finishingrate', verbose_name='finishing rate'),
        ),
        migrations.AddField(
            model_name='productfinishingoption',
            name='product',
            field=models.ForeignKey(help_text='Product this option applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='finishing_options', to='catalog.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='catalog_category_shop_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('shop__isnull', True)), fields=('slug',), name='catalog_category_global_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='productfinishingoption',
            constraint=models.UniqueConstraint(fields=('product', 'finishing_rate'), name='unique_product_finishing'),
        ),
    ]
