# Generated by Django 5.2.11 on 2026-04-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='booklet_max_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum page count allowed for this booklet product.', null=True, verbose_name='booklet max pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='booklet_min_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum page count allowed for this booklet product.', null=True, verbose_name='booklet min pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='booklet_page_multiple',
            field=models.PositiveIntegerField(default=4, help_text='Page count must be a multiple of this value. 4 = standard saddle-stitch (cover + inners both fold to 4). Service layer rounds input_pages up to the nearest multiple.', verbose_name='booklet page multiple'),
        ),
        migrations.AddField(
            model_name='product',
            name='creep_warning_start_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Page count above which inner-page creep / trimming caution is surfaced. Used later for thick-booklet UX warnings.', null=True, verbose_name='creep warning start pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_binding_type',
            field=models.CharField(blank=True, choices=[('SADDLE_STITCH', 'Saddle Stitch'), ('PERFECT_BIND', 'Perfect Bind')], default='', help_text='Default binding method for booklets. Leave blank for flat products.', max_length=20, verbose_name='default binding type'),
        ),
        migrations.AddField(
            model_name='product',
            name='perfect_bind_recommended_min_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Page count from which perfect binding is recommended. Used by service layer to suggest a binding upgrade.', null=True, verbose_name='perfect bind recommended min pages'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('BOOKLET', 'Booklet')], default='FLAT', help_text='FLAT = standard single-sheet job. BOOKLET = multi-page bound product.', max_length=20, verbose_name='product kind'),
        ),
        migrations.AddField(
            model_name='product',
            name='saddle_stitch_recommended_max_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Transparent guidance threshold: saddle stitch is practical up to this page count. Above this, service layer may warn and recommend perfect binding. Not a hard limit — a UX trust-building signal.', null=True, verbose_name='saddle stitch recommended max pages'),
        ),
    ]
