# Generated by Django 5.2.11 on 2026-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_quantity',
            field=models.PositiveIntegerField(default=100, help_text='Minimum order quantity for price range calculation.', verbose_name='min quantity'),
        ),
    ]
