# Generated by Django 5.2.11 on 2026-03-10 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_add_paper_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_machine',
            field=models.ForeignKey(blank=True, help_text='Default printing machine for this product. Clients can override when adding to quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_products', to='inventory.machine', verbose_name='default machine'),
        ),
    ]
