# Generated by Django 5.2.11 on 2026-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_product_default_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this category is visible in SEO and gallery.', verbose_name='is active'),
        ),
    ]
