# Generated by Django 5.2.11 on 2026-03-03 19:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_update_min_quantity_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.50'), help_text='Minimum printable area in m² for LARGE_FORMAT products. Default 0.5 m².', max_digits=8, null=True, verbose_name='min area (m²)'),
        ),
    ]
