# Generated by Django 5.2.11 on 2026-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_pricing_snapshot_and_min_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('UNAVAILABLE', 'Unavailable')], default='DRAFT', help_text='DRAFT = not visible to buyers. PUBLISHED = visible if shop pricing ready. UNAVAILABLE = hidden.', max_length=20, verbose_name='status'),
        ),
    ]
