# Generated by Django 5.2.11 on 2026-03-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_product_status_and_pricing_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_sheet_sizes',
            field=models.JSONField(blank=True, help_text='List of allowed parent sheet codes (e.g. ["A4","A3","SRA3"]). Empty = no restriction.', null=True, verbose_name='allowed sheet sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_height_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Max finished height (e.g. 148 for A6). Rejects larger sizes.', null=True, verbose_name='max height (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_width_mm',
            field=models.PositiveIntegerField(blank=True, help_text='Max finished width (e.g. 105 for A6 business cards). Rejects larger sizes.', null=True, verbose_name='max width (mm)'),
        ),
    ]
