# Generated by Django 5.2.11 on 2026-04-02 20:50

from django.db import migrations, models


def backfill_standard_turnaround_hours(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.exclude(turnaround_days__isnull=True):
        if product.standard_turnaround_hours:
            continue
        product.standard_turnaround_hours = product.turnaround_days * 8
        product.save(update_fields=['standard_turnaround_hours'])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_product_turnaround_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buffer_hours',
            field=models.PositiveIntegerField(default=0, help_text='Safety buffer added on top of production time.', verbose_name='buffer hours'),
        ),
        migrations.AddField(
            model_name='product',
            name='queue_hours',
            field=models.PositiveIntegerField(default=0, help_text='Current queue delay in working hours. Safe default for future dynamic queueing.', verbose_name='queue hours'),
        ),
        migrations.AddField(
            model_name='product',
            name='rush_available',
            field=models.BooleanField(default=False, help_text='Whether this product can be produced on a rush turnaround.', verbose_name='rush available'),
        ),
        migrations.AddField(
            model_name='product',
            name='rush_turnaround_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Optional faster turnaround in working hours when rush service is available.', null=True, verbose_name='rush turnaround hours'),
        ),
        migrations.AddField(
            model_name='product',
            name='standard_turnaround_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Production turnaround in working hours for standard service.', null=True, verbose_name='standard turnaround hours'),
        ),
        migrations.RunPython(backfill_standard_turnaround_hours, noop),
    ]
