# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFinishingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('charge_unit', models.CharField(choices=[('PER_PIECE', 'Per Piece'), ('PER_SHEET', 'Per Sheet'), ('PER_SQM', 'Per Square Meter'), ('FLAT', 'Flat')], default='PER_PIECE', max_length=20, verbose_name='charge unit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('setup_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='setup fee')),
                ('min_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='min quantity')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'demo finishing rate',
                'verbose_name_plural': 'demo finishing rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DemoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=255, verbose_name='material type')),
                ('unit', models.CharField(default='SQM', max_length=20, verbose_name='unit')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='selling price per unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'demo material',
                'verbose_name_plural': 'demo materials',
                'ordering': ['material_type'],
            },
        ),
        migrations.CreateModel(
            name='DemoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('category', models.CharField(choices=[('business_cards', 'Business Cards'), ('flyers', 'Flyers'), ('booklets', 'Booklets'), ('magazines', 'Magazines'), ('notebooks', 'Notebooks'), ('billboards', 'Billboards'), ('rollup_banners', 'Roll-up Banners')], default='flyers', max_length=50, verbose_name='category')),
                ('pricing_mode', models.CharField(choices=[('SHEET', 'Sheet (copies per sheet)'), ('LARGE_FORMAT', 'Large Format (by area)')], default='SHEET', max_length=20, verbose_name='pricing mode')),
                ('default_finished_width_mm', models.PositiveIntegerField(default=0, verbose_name='finished width (mm)')),
                ('default_finished_height_mm', models.PositiveIntegerField(default=0, verbose_name='finished height (mm)')),
                ('default_sides', models.CharField(choices=[('SIMPLEX', 'Single-sided'), ('DUPLEX', 'Double-sided')], default='DUPLEX', max_length=10, verbose_name='default sides')),
                ('min_quantity', models.PositiveIntegerField(default=100, verbose_name='min quantity')),
                ('default_sheet_size', models.CharField(blank=True, default='SRA3', max_length=20, verbose_name='default sheet size')),
                ('copies_per_sheet', models.PositiveIntegerField(default=1, help_text='How many finished pieces fit on one sheet (imposition).', verbose_name='copies per sheet')),
                ('min_gsm', models.PositiveIntegerField(blank=True, help_text='Minimum paper weight allowed.', null=True, verbose_name='min GSM')),
                ('max_gsm', models.PositiveIntegerField(blank=True, help_text='Maximum paper weight allowed.', null=True, verbose_name='max GSM')),
                ('badge', models.CharField(blank=True, default='', help_text='Optional badge (e.g. Popular).', max_length=50, verbose_name='badge')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'demo product',
                'verbose_name_plural': 'demo products',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemoPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], max_length=20, verbose_name='sheet size')),
                ('gsm', models.PositiveIntegerField(help_text='Paper weight (grams per square metre).', verbose_name='GSM')),
                ('paper_type', models.CharField(choices=[('UNCOATED', 'Uncoated'), ('COATED', 'Coated'), ('GLOSS', 'Gloss')], default='GLOSS', max_length=20, verbose_name='paper type')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='selling price per sheet')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'demo paper',
                'verbose_name_plural': 'demo papers',
                'ordering': ['sheet_size', 'gsm'],
                'constraints': [models.UniqueConstraint(fields=('sheet_size', 'gsm', 'paper_type'), name='unique_demo_paper')],
            },
        ),
        migrations.CreateModel(
            name='DemoPrintingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('SRA3', 'SRA3')], max_length=20, verbose_name='sheet size')),
                ('color_mode', models.CharField(choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='COLOR', max_length=10, verbose_name='color mode')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='single-sided price per sheet')),
                ('double_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='double-sided price per sheet')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'demo printing rate',
                'verbose_name_plural': 'demo printing rates',
                'ordering': ['sheet_size', 'color_mode'],
                'constraints': [models.UniqueConstraint(fields=('sheet_size', 'color_mode'), name='unique_demo_printing_rate')],
            },
        ),
        migrations.CreateModel(
            name='DemoProductFinishingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('price_adjustment', models.DecimalField(blank=True, decimal_places=2, help_text='Override finishing price. Blank = use rate price.', max_digits=12, null=True, verbose_name='price adjustment')),
                ('finishing_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='demo.demofinishingrate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_finishing_options', to='demo.demoproduct')),
            ],
            options={
                'verbose_name': 'demo product finishing option',
                'verbose_name_plural': 'demo product finishing options',
                'ordering': ['product', 'finishing_rate'],
            },
        ),
        migrations.AddField(
            model_name='demoproduct',
            name='finishing_options',
            field=models.ManyToManyField(blank=True, related_name='demo_products', through='demo.DemoProductFinishingOption', to='demo.demofinishingrate', verbose_name='finishing options'),
        ),
        migrations.AddConstraint(
            model_name='demoproductfinishingoption',
            constraint=models.UniqueConstraint(fields=('product', 'finishing_rate'), name='unique_demo_product_finishing'),
        ),
    ]
