# Generated by Django 5.2.11 on 2026-09-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowManager',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='key')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=8)),
                ('tag', models.CharField(blank=True, default='', max_length=255)),
                ('on_time', models.PositiveSmallIntegerField(default=0, verbose_name='on-time percent')),
                ('hue', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'workflow manager',
                'verbose_name_plural': 'workflow managers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPrinter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='key')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('caps', models.JSONField(default=list, verbose_name='capabilities')),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('jobs_done', models.PositiveIntegerField(default=0)),
                ('on_time', models.PositiveSmallIntegerField(default=0, verbose_name='on-time percent')),
                ('initials', models.CharField(max_length=8)),
                ('hue', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'workflow printer',
                'verbose_name_plural': 'workflow printers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='key')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buyer_id', models.CharField(max_length=32)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_company', models.CharField(max_length=255)),
                ('specs', models.JSONField(default=dict, verbose_name='specification')),
                ('proof_img', models.CharField(blank=True, default='', max_length=255, verbose_name='proof image')),
                ('status', models.CharField(choices=[('on-track', 'On track'), ('at-risk', 'At risk'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('completed', 'Completed')], default='on-track', max_length=16)),
                ('custody', models.CharField(choices=[('awaiting', 'Awaiting'), ('held', 'Held'), ('released', 'Released')], default='awaiting', max_length=16)),
                ('stage', models.CharField(choices=[('quote', 'Quote'), ('artwork', 'Artwork'), ('approval', 'Approval'), ('payment', 'Payment'), ('production', 'Production'), ('printing', 'Printing'), ('finishing', 'Finishing'), ('qc', 'Quality Control'), ('delivery', 'Delivery'), ('completed', 'Completed')], default='quote', max_length=16)),
                ('press', models.CharField(blank=True, choices=[('accept', 'Accept'), ('ready', 'Ready'), ('active', 'Active'), ('hold', 'Hold')], max_length=16, null=True)),
                ('progress', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('owner', models.JSONField(default=dict, verbose_name='ball holder')),
                ('eta', models.CharField(blank=True, default='', max_length=64)),
                ('placed_at', models.CharField(blank=True, default='', max_length=64)),
                ('dispute', models.JSONField(blank=True, null=True)),
                ('history', models.JSONField(default=list, verbose_name='stage events')),
                ('feed', models.JSONField(default=list, verbose_name='activity feed')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workflow.workflowmanager')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workflow.workflowprinter')),
            ],
            options={
                'verbose_name': 'workflow job',
                'verbose_name_plural': 'workflow jobs',
                'ordering': ['-placed_at'],
            },
        ),
    ]
