# Generated by Django 5.2.11 on 2026-03-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. Westlands, Nairobi).', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated from name if blank.', max_length=100, unique=True, verbose_name='slug')),
                ('location_type', models.CharField(choices=[('neighborhood', 'Neighborhood'), ('city', 'City'), ('county', 'County')], default='neighborhood', help_text='Location type for hierarchy and display.', max_length=20, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is visible in SEO pages.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location (e.g. Westlands → Nairobi).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='locations_slug_idx'), models.Index(fields=['is_active'], name='locations_active_idx')],
            },
        ),
    ]
