# Generated by Django 5.2.11 on 2026-03-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City (e.g. Nairobi, Mombasa).', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(blank=True, default='', help_text='County or region (optional).', max_length=100, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default='', help_text='SEO description for the location page.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geo display and search.', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geo display and search.', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
