# Generated by Django 5.2.11 on 2026-03-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_add_location_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_place_id',
            field=models.CharField(blank=True, default='', help_text='Stable identifier from Google Places for reuse and geocoding.', max_length=255, verbose_name='Google Place ID'),
        ),
    ]
