# Generated by Django 5.2.11 on 2026-07-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('quote_request_submitted', 'New quote request'), ('quote_request_sent', 'Request sent'), ('quote_sent', 'Quote sent'), ('quote_revised', 'Quote revised'), ('quote_accepted', 'Quote accepted'), ('shop_question_asked', 'Shop question'), ('buyer_clarification_sent', 'Buyer clarification'), ('request_declined', 'Request declined'), ('quote_request_cancelled', 'Request cancelled'), ('job_status_updated', 'Job status updated'), ('payment_confirmed', 'Payment confirmed'), ('artwork_required', 'Artwork required'), ('job_ready_to_start', 'Job ready to start'), ('job_created', 'Job created')], max_length=50, verbose_name='type')),
                ('object_type', models.CharField(blank=True, default='', help_text='e.g. quote_request, quote, production_order', max_length=50, verbose_name='object type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object id')),
                ('message', models.TextField(default='', verbose_name='message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notif_user_created_idx'), models.Index(fields=['user', 'read_at'], name='notif_user_read_idx')],
            },
        ),
    ]
