# Generated by Django 5.2.11 on 2026-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('quote_request_submitted', 'New quote request'), ('quote_request_sent', 'Request sent'), ('shop_quote_sent', 'Quote sent'), ('shop_quote_revised', 'Quote revised'), ('shop_quote_accepted', 'Quote accepted'), ('shop_question_asked', 'Shop question'), ('buyer_clarification_sent', 'Buyer clarification'), ('request_declined', 'Request declined'), ('quote_request_cancelled', 'Request cancelled'), ('job_status_updated', 'Job status updated')], max_length=50, verbose_name='type'),
        ),
    ]
