# Generated by Django 5.2.11 on 2026-03-16 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='User who triggered this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_triggered', to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('quote_request_submitted', 'New quote request'), ('shop_quote_sent', 'Quote sent'), ('shop_quote_revised', 'Quote revised'), ('shop_quote_accepted', 'Quote accepted'), ('request_declined', 'Request declined'), ('quote_request_cancelled', 'Request cancelled'), ('job_status_updated', 'Job status updated')], max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient'),
        ),
    ]
