# Generated by Django 5.2.11 on 2026-03-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(blank=True, default='', help_text='Customer name.', max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, default='', help_text='Customer phone number.', max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, help_text='Customer email address.', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'customer inquiry',
                'verbose_name_plural': 'customer inquiries',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('customer_name', models.CharField(default='', help_text='Name of the customer.', max_length=255, verbose_name='customer name')),
                ('customer_email', models.EmailField(blank=True, help_text='Email address of the customer.', max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(blank=True, default='', help_text='Phone number of the customer.', max_length=50, verbose_name='customer phone')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PRICED', 'Priced'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', help_text='Current status of the quote request.', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes for the quote.', verbose_name='notes')),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the quote.', max_digits=12, null=True, verbose_name='total')),
                ('pricing_locked_at', models.DateTimeField(blank=True, help_text='When pricing was locked.', null=True, verbose_name='pricing locked at')),
                ('whatsapp_message', models.TextField(blank=True, default='', help_text='Message sent via WhatsApp when quote was sent.', verbose_name='whatsapp message')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the quote was sent to the customer.', null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this quote request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer_inquiry', models.ForeignKey(blank=True, help_text='Optional linked customer inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='quotes.customerinquiry', verbose_name='customer inquiry')),
                ('shop', models.ForeignKey(help_text='Shop this quote request is for.', on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='shops.shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'quote request',
                'verbose_name_plural': 'quote requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('item_type', models.CharField(choices=[('PRODUCT', 'Product'), ('CUSTOM', 'Custom')], default='PRODUCT', help_text='PRODUCT = catalog product; CUSTOM = client-specified.', max_length=20, verbose_name='item type')),
                ('title', models.CharField(blank=True, default='', help_text='Display title; required for CUSTOM items.', max_length=120, verbose_name='title')),
                ('spec_text', models.TextField(blank=True, default='', help_text='Free-text spec from client (e.g. dimensions, qty).', verbose_name='spec text')),
                ('has_artwork', models.BooleanField(default=False, help_text='If true, design service defaults off (client provides art).', verbose_name='has artwork')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered.', verbose_name='quantity')),
                ('pricing_mode', models.CharField(blank=True, choices=[('SHEET', 'Sheet'), ('LARGE_FORMAT', 'Large Format')], default='', help_text='Sheet or large format pricing.', max_length=20, verbose_name='pricing mode')),
                ('chosen_width_mm', models.PositiveIntegerField(blank=True, help_text='Chosen width in millimeters for large format.', null=True, verbose_name='chosen width (mm)')),
                ('chosen_height_mm', models.PositiveIntegerField(blank=True, help_text='Chosen height in millimeters for large format.', null=True, verbose_name='chosen height (mm)')),
                ('sides', models.CharField(blank=True, choices=[('SIMPLEX', 'Simplex'), ('DUPLEX', 'Duplex')], default='', help_text='Simplex (1-sided) or duplex (2-sided).', max_length=10, verbose_name='sides')),
                ('color_mode', models.CharField(blank=True, choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='', help_text='Black & white or color.', max_length=10, verbose_name='color mode')),
                ('special_instructions', models.TextField(blank=True, default='', help_text='Special instructions for this item.', verbose_name='special instructions')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated: line_total/quantity. SHEET: paper + PrintingRate; LARGE_FORMAT: material×area. If 0, fill QuoteItem.paper (+ machine+sides+color) or material+chosen_width+height.', max_digits=12, null=True, verbose_name='unit price')),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated on save. SHEET: paper.selling_price×sheets + PrintingRate×sheets + finishing. LARGE_FORMAT: material.selling_price×area_sqm + finishing.', max_digits=12, null=True, verbose_name='line total')),
                ('pricing_snapshot', models.JSONField(blank=True, help_text='Full pricing breakdown at computation time. Stores imposition_count, sheets_needed, area_m2, paper_cost, print_cost, finishing_total, services_total, and line items.', null=True, verbose_name='pricing snapshot')),
                ('pricing_locked_at', models.DateTimeField(blank=True, help_text='When this item was priced.', null=True, verbose_name='pricing locked at')),
                ('machine', models.ForeignKey(blank=True, help_text='Machine to use for printing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='inventory.machine', verbose_name='machine')),
                ('material', models.ForeignKey(blank=True, help_text='Material for large format (required for LARGE_FORMAT mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='pricing.material', verbose_name='material')),
                ('paper', models.ForeignKey(blank=True, help_text='Paper for sheet printing (required for SHEET mode).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='inventory.paper', verbose_name='paper')),
                ('product', models.ForeignKey(blank=True, help_text='Product for this quote item (required for PRODUCT type).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.product', verbose_name='product')),
                ('quote_request', models.ForeignKey(help_text='Quote request this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest', verbose_name='quote request')),
            ],
            options={
                'verbose_name': 'quote item',
                'verbose_name_plural': 'quote items',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='QuoteShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('token', models.CharField(db_index=True, help_text='URL-safe random token for public access.', max_length=64, unique=True, verbose_name='token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null = no expiry.', null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this share link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_share_links', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('quote', models.ForeignKey(help_text='Quote this share link points to.', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='quotes.quoterequest', verbose_name='quote')),
            ],
            options={
                'verbose_name': 'quote share link',
                'verbose_name_plural': 'quote share links',
            },
        ),
        migrations.CreateModel(
            name='QuoteItemFinishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('coverage_qty', models.DecimalField(blank=True, decimal_places=4, help_text='Quantity of finishing applied.', max_digits=12, null=True, verbose_name='coverage quantity')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional override for the finishing price.', max_digits=12, null=True, verbose_name='price override')),
                ('apply_to_sides', models.CharField(blank=True, choices=[('SINGLE', 'Single-sided'), ('DOUBLE', 'Double-sided'), ('BOTH', 'Both (follows print)')], default='BOTH', help_text='Single-sided, double-sided, or both (uses print sides).', max_length=10, verbose_name='apply to sides')),
                ('finishing_rate', models.ForeignKey(help_text='Finishing rate for this item.', on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_finishings', to='pricing.finishingrate', verbose_name='finishing rate')),
                ('quote_item', models.ForeignKey(help_text='Quote item this finishing applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='finishings', to='quotes.quoteitem', verbose_name='quote item')),
            ],
            options={
                'verbose_name': 'quote item finishing',
                'verbose_name_plural': 'quote item finishings',
                'constraints': [models.UniqueConstraint(fields=('quote_item', 'finishing_rate'), name='unique_quote_item_finishing')],
            },
        ),
        migrations.CreateModel(
            name='QuoteItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('is_selected', models.BooleanField(default=False, help_text='I need design help.', verbose_name='is selected')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Seller override (negotiable).', max_digits=12, null=True, verbose_name='price override')),
                ('note', models.CharField(blank=True, default='', help_text='Optional note.', max_length=255, verbose_name='note')),
                ('quote_item', models.ForeignKey(help_text='Quote item this service applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='quotes.quoteitem', verbose_name='quote item')),
                ('service_rate', models.ForeignKey(help_text='Service rate (e.g. Design).', on_delete=django.db.models.deletion.CASCADE, related_name='quote_item_services', to='pricing.servicerate', verbose_name='service rate')),
            ],
            options={
                'verbose_name': 'quote item service',
                'verbose_name_plural': 'quote item services',
                'constraints': [models.UniqueConstraint(fields=('quote_item', 'service_rate'), name='unique_quote_item_service')],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('is_selected', models.BooleanField(default=False, help_text='Pickup=false, Delivery=true.', verbose_name='is selected')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance for TIERED_DISTANCE. Seller can set later.', max_digits=12, null=True, verbose_name='distance (km)')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Seller override (e.g. negotiated delivery).', max_digits=12, null=True, verbose_name='price override')),
                ('quote_request', models.ForeignKey(help_text='Quote request this service applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='quotes.quoterequest', verbose_name='quote request')),
                ('service_rate', models.ForeignKey(help_text='Service rate (e.g. Delivery).', on_delete=django.db.models.deletion.CASCADE, related_name='quote_request_services', to='pricing.servicerate', verbose_name='service rate')),
            ],
            options={
                'verbose_name': 'quote request service',
                'verbose_name_plural': 'quote request services',
                'constraints': [models.UniqueConstraint(fields=('quote_request', 'service_rate'), name='unique_quote_request_service')],
            },
        ),
    ]
