# Generated by Django 5.2.11 on 2026-03-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, help_text='Full pricing breakdown at computation time. Stores imposition_count, sheets_needed, area_m2, paper_cost, print_cost, finishing_total, services_total, and line items.', null=True, verbose_name='pricing snapshot'),
        ),
    ]
