# Generated by Django 5.2.11 on 2026-03-08 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_paper_is_default'),
        ('pricing', '0002_add_printing_rate_is_default'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='item_spec_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen snapshot of buyer choices at add-to-quote time. Never mutates the source product template.', null=True, verbose_name='item spec snapshot'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='True when pricing cannot be calculated (missing setup). Item is saved; seller reviews and prices manually.', verbose_name='needs review'),
        ),
        migrations.CreateModel(
            name='QuoteItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('component_type', models.CharField(choices=[('BODY', 'Body'), ('COVER', 'Cover'), ('INSERT', 'Insert')], default='BODY', help_text='BODY = single-part; COVER/INSERT = booklet parts.', max_length=20, verbose_name='component type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower = first).', verbose_name='display order')),
                ('chosen_width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='chosen width (mm)')),
                ('chosen_height_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='chosen height (mm)')),
                ('sides', models.CharField(blank=True, choices=[('SIMPLEX', 'Simplex'), ('DUPLEX', 'Duplex')], default='', max_length=10, verbose_name='sides')),
                ('color_mode', models.CharField(blank=True, choices=[('BW', 'Black & White'), ('COLOR', 'Color')], default='', max_length=10, verbose_name='color mode')),
                ('material', models.ForeignKey(blank=True, help_text='Material for LARGE_FORMAT mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_item_components', to='pricing.material', verbose_name='material')),
                ('paper', models.ForeignKey(blank=True, help_text='Paper for SHEET mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_item_components', to='inventory.paper', verbose_name='paper')),
                ('quote_item', models.ForeignKey(help_text='Quote item this component belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='quotes.quoteitem', verbose_name='quote item')),
            ],
            options={
                'verbose_name': 'quote item component',
                'verbose_name_plural': 'quote item components',
                'ordering': ['quote_item', 'display_order', 'pk'],
            },
        ),
    ]
