# Generated by Django 5.2.11 on 2026-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='binding_type',
            field=models.CharField(blank=True, choices=[('SADDLE_STITCH', 'Saddle Stitch'), ('PERFECT_BIND', 'Perfect Bind')], default='', help_text='Binding method chosen for this booklet item. Blank for flat jobs.', max_length=20, verbose_name='binding type'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='input_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Raw page count as entered by the buyer (before normalisation).', null=True, verbose_name='input pages'),
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='normalized_pages',
            field=models.PositiveIntegerField(blank=True, help_text='Page count rounded up to the nearest booklet_page_multiple. Stored so pricing components can reference it without re-computing.', null=True, verbose_name='normalized pages'),
        ),
        migrations.AddField(
            model_name='quoteitemcomponent',
            name='pages',
            field=models.PositiveIntegerField(blank=True, help_text='Page count for this component. COVER = typically 4; INSERT = normalized_pages − 4. Null for flat (BODY) components.', null=True, verbose_name='pages'),
        ),
    ]
