# Generated by Django 5.2.11 on 2026-03-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_pricing_snapshot_and_min_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('name', models.CharField(blank=True, default='', help_text='Customer name.', max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, default='', help_text='Customer phone number.', max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, help_text='Customer email address.', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'customer inquiry',
                'verbose_name_plural': 'customer inquiries',
            },
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was sent to the customer.', null=True, verbose_name='sent at'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='whatsapp_message',
            field=models.TextField(blank=True, default='', help_text='Message sent via WhatsApp when quote was sent.', verbose_name='whatsapp message'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PRICED', 'Priced'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', help_text='Current status of the quote request.', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='customer_inquiry',
            field=models.ForeignKey(blank=True, help_text='Optional linked customer inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='quotes.customerinquiry', verbose_name='customer inquiry'),
        ),
    ]
