# Generated by Django 5.2.11 on 2026-03-15 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_item_spec_snapshot_and_components'),
        ('shops', '0005_add_google_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['shop', 'status'], name='quotes_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['shop', '-created_at'], name='quotes_shop_created_idx'),
        ),
    ]
