# Generated by Django 5.2.11 on 2026-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quoterequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_shop_action', 'Awaiting shop action'), ('accepted', 'Accepted by shop'), ('awaiting_client_reply', 'Awaiting client reply'), ('viewed', 'Viewed'), ('quoted', 'Quoted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', help_text='Customer request lifecycle: draft → submitted → quoted → accepted/closed.', max_length=32, verbose_name='status'),
        ),
    ]
