# Generated by Django 5.2.11 on 2026-03-05 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_add_customer_inquiry_whatsapp_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('token', models.CharField(db_index=True, help_text='URL-safe random token for public access.', max_length=64, unique=True, verbose_name='token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null = no expiry.', null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this share link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_share_links', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('quote', models.ForeignKey(help_text='Quote this share link points to.', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='quotes.quoterequest', verbose_name='quote')),
            ],
            options={
                'verbose_name': 'quote share link',
                'verbose_name_plural': 'quote share links',
            },
        ),
    ]
