# Generated by Django 5.2.11 on 2026-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_expand_quoterequestmessage_for_inbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestmessage',
            name='conversation_type',
            field=models.CharField(blank=True, choices=[('client_question', 'Client question'), ('client_counter_offer', 'Client counter offer'), ('client_change_request', 'Client change request'), ('client_file_update', 'Client file update'), ('shop_reply', 'Shop reply'), ('system_update', 'System update')], default='', help_text='Structured quote conversation type for negotiation and follow-up messages.', max_length=40, verbose_name='conversation type'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_finishing',
            field=models.JSONField(blank=True, help_text='Optional proposed finishing selections in a conversation message.', null=True, verbose_name='proposed finishing'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_gsm',
            field=models.CharField(blank=True, default='', help_text='Optional proposed gsm in a conversation message.', max_length=100, verbose_name='proposed gsm'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_material',
            field=models.CharField(blank=True, default='', help_text='Optional proposed material in a conversation message.', max_length=255, verbose_name='proposed material'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional proposed price in a conversation message.', max_digits=12, null=True, verbose_name='proposed price'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Optional proposed quantity in a conversation message.', null=True, verbose_name='proposed quantity'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_size',
            field=models.CharField(blank=True, default='', help_text='Optional proposed size in a conversation message.', max_length=255, verbose_name='proposed size'),
        ),
        migrations.AddField(
            model_name='quoterequestmessage',
            name='proposed_turnaround',
            field=models.CharField(blank=True, default='', help_text='Optional proposed turnaround text in a conversation message.', max_length=255, verbose_name='proposed turnaround'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the client accepted this quote.', null=True, verbose_name='accepted at'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the client rejected or did not select this quote.', null=True, verbose_name='rejected at'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='rejection_message',
            field=models.TextField(blank=True, default='', help_text='Optional detailed rejection message from the client.', verbose_name='rejection message'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', help_text='Short client rejection reason or not-selected reason.', max_length=255, verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='quoterequestmessage',
            name='message_type',
            field=models.CharField(choices=[('quote_request_created', 'Quote request created'), ('quote_response_sent', 'Quote response sent'), ('quote_question', 'Quote question'), ('quote_accepted', 'Quote accepted'), ('quote_rejected', 'Quote rejected'), ('quote_conversation', 'Quote conversation'), ('system_notice', 'System notice'), ('email_delivery_failed', 'Email delivery failed')], default='system_notice', help_text='Normalized message event type for inbox/outbox.', max_length=40, verbose_name='message type'),
        ),
    ]
