# Generated by Django 5.2.11 on 2026-05-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoterequestmessage_conversation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='End client this request was created for when a partner submits on their behalf.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_requested_for_me', to=settings.AUTH_USER_MODEL, verbose_name='on behalf of'),
        ),
    ]
