# Generated by Django 5.2.11 on 2026-05-23 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_shopquote_client_pricing_fields'),
        ('shops', '0004_shop_mvp_rate_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, help_text='Print Manager / Partner assigned to coordinate this request before production shop selection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='assigned manager'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop this quote request is for when the request is already shop-bound.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='shops.shop', verbose_name='shop'),
        ),
    ]
