# Generated by Django 5.2.11 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quoterequest_assigned_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopquote',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the client-facing quote expires.', null=True, verbose_name='expires at'),
        ),
    ]
