# Generated by Django 5.2.11 on 2026-03-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_add_google_place_id"),
        ("quotes", "0008_remove_quote_request_legacy_fields"),
        ("shops", "0005_add_google_place_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Full address for delivery (street, building, etc.).', verbose_name='delivery address'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_location',
            field=models.ForeignKey(blank=True, help_text='Area/neighborhood for delivery (e.g. Westlands, Kilimani).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='locations.location', verbose_name='delivery location'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='delivery_preference',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='', help_text='Customer preference: pickup at shop or delivery.', max_length=20, verbose_name='delivery preference'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='note',
            field=models.TextField(blank=True, default='', help_text="Shop's note to customer (e.g. conditions, clarifications).", verbose_name='note'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='revision_number',
            field=models.PositiveIntegerField(default=1, help_text='Revision count for this quote request (1 = first, 2 = first revision, etc.).', verbose_name='revision number'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='turnaround_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected turnaround in days (e.g. ready in 3 days).', null=True, verbose_name='turnaround (days)'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='shop_quote',
            field=models.ForeignKey(blank=True, help_text='Shop quote this item is priced in (set when shop prices).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.shopquote', verbose_name='shop quote'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('viewed', 'Viewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', help_text='Customer request lifecycle: draft → submitted → quoted → accepted/closed.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='quotesharelink',
            name='shop_quote',
            field=models.ForeignKey(help_text='Shop quote this share link points to.', on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='quotes.shopquote', verbose_name='shop quote'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Shop user who created/sent this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_quotes', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='pricing_locked_at',
            field=models.DateTimeField(blank=True, help_text='When pricing was locked.', null=True, verbose_name='pricing locked at'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='quote_request',
            field=models.ForeignKey(help_text='Quote request this offer responds to.', on_delete=django.db.models.deletion.CASCADE, related_name='shop_quotes', to='quotes.quoterequest', verbose_name='quote request'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was sent to the customer.', null=True, verbose_name='sent at'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='shop',
            field=models.ForeignKey(help_text='Shop that sent this quote.', on_delete=django.db.models.deletion.CASCADE, related_name='shop_quotes', to='shops.shop', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='sent', help_text='Shop offer lifecycle: sent → accepted/declined/expired/revised.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the quote.', max_digits=12, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='whatsapp_message',
            field=models.TextField(blank=True, default='', help_text='Message sent via WhatsApp when quote was sent.', verbose_name='whatsapp message'),
        ),
        migrations.CreateModel(
            name='QuoteRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('file', models.FileField(help_text='Uploaded file (artwork, spec, etc.).', upload_to='quote_requests/%Y/%m/', verbose_name='file')),
                ('name', models.CharField(blank=True, default='', help_text='Optional display name for the file.', max_length=255, verbose_name='name')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quoterequest', verbose_name='quote request')),
            ],
            options={
                'verbose_name': 'quote request attachment',
                'verbose_name_plural': 'quote request attachments',
            },
        ),
        migrations.CreateModel(
            name='ShopQuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('file', models.FileField(help_text='Uploaded file (proof, revised spec, etc.).', upload_to='shop_quotes/%Y/%m/', verbose_name='file')),
                ('name', models.CharField(blank=True, default='', help_text='Optional display name for the file.', max_length=255, verbose_name='name')),
                ('shop_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.shopquote', verbose_name='shop quote')),
            ],
            options={
                'verbose_name': 'shop quote attachment',
                'verbose_name_plural': 'shop quote attachments',
            },
        ),
    ]
