# Generated by Django 5.2.11 on 2026-05-25 19:59

import django.db.models.deletion
import quotes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_shopquote_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotedraft',
            name='artwork_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotedraft',
            name='artwork_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quotedraft',
            name='guest_session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='quotedraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_drafts_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PendingArtworkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('file', models.FileField(upload_to=quotes.models.pending_artwork_upload_to, verbose_name='file')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pending_artwork', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pending artwork upload',
                'verbose_name_plural': 'pending artwork uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'expires_at'], name='pending_art_exp_idx')],
            },
        ),
    ]
