# Generated by Django 5.2.11 on 2026-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_backfill_quote_files_for_all_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedraftfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='quotedraftfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
    ]
