# Generated by Django 5.2.11 on 2026-03-26 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_product_turnaround_days'),
        ('quotes', '0012_alter_quotedraftfile_created_at_and_more'),
        ('shops', '0006_shopmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitemfinishing',
            name='selected_side',
            field=models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], default='both', help_text='Explicit selected finishing side for preview and pricing.', max_length=10, verbose_name='selected side'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='request_reference',
            field=models.CharField(blank=True, default='', help_text='Stable reference for customer-facing quote requests.', max_length=50, verbose_name='request reference'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='request_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen request payload used when the customer submitted the request.', null=True, verbose_name='request snapshot'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='quote_reference',
            field=models.CharField(blank=True, default='', help_text='Stable shop response reference.', max_length=50, verbose_name='quote reference'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='response_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen response payload for PDF/share rendering.', null=True, verbose_name='response snapshot'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='revised_pricing_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen revised pricing payload for this response.', null=True, verbose_name='revised pricing snapshot'),
        ),
        migrations.AlterField(
            model_name='shopquote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('modified', 'Modified'), ('sent', 'Sent'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Shop offer lifecycle: sent → accepted/declined/expired/revised.', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='QuoteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('draft_reference', models.CharField(blank=True, default='', max_length=50)),
                ('custom_product_snapshot', models.JSONField(blank=True, null=True)),
                ('calculator_inputs_snapshot', models.JSONField()),
                ('pricing_snapshot', models.JSONField(blank=True, null=True)),
                ('request_details_snapshot', models.JSONField(blank=True, null=True)),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_quote_drafts', to='catalog.product')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_drafts_v2', to='shops.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_drafts_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quote draft',
                'verbose_name_plural': 'quote drafts',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='source_draft',
            field=models.ForeignKey(blank=True, help_text='Draft that generated this request, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_requests', to='quotes.quotedraft', verbose_name='source draft'),
        ),
    ]
