# Generated by Django 5.2.11 on 2026-04-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quoterequestmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequestmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='quoterequestmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.', verbose_name='updated at'),
        ),
    ]
