# Generated by Django 5.2.11 on 2026-04-02 20:50

from django.db import migrations, models


def backfill_turnaround_hours(apps, schema_editor):
    ShopQuote = apps.get_model('quotes', 'ShopQuote')
    for quote in ShopQuote.objects.exclude(turnaround_days__isnull=True):
        if quote.turnaround_hours:
            continue
        quote.turnaround_hours = quote.turnaround_days * 8
        quote.save(update_fields=['turnaround_hours'])


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_quoterequestmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopquote',
            name='estimated_ready_at',
            field=models.DateTimeField(blank=True, help_text='Projected ready datetime based on working hours.', null=True, verbose_name='estimated ready at'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='human_ready_text',
            field=models.CharField(blank=True, default='', help_text='Human-friendly ready promise shown to customers.', max_length=255, verbose_name='human ready text'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='turnaround_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Expected turnaround in working hours.', null=True, verbose_name='turnaround (hours)'),
        ),
        migrations.AddField(
            model_name='shopquote',
            name='turnaround_label',
            field=models.CharField(blank=True, default='', help_text='Centralized turnaround label such as Same day or Standard.', max_length=50, verbose_name='turnaround label'),
        ),
        migrations.RunPython(backfill_turnaround_hours, noop),
    ]
